// AirCargoNexust/src/components/DataTable.svelte
<script lang="ts">
  import { ChevronUp, ChevronDown } from 'lucide-svelte';

  let {
    columns,
    data,
    selectable = false,
    selectedIds = $bindable(new Set<string>())
  }: {
    columns: Array<{
      key: string;
      label: string;
      sortable?: boolean;
      width?: string;
      render?: (value: unknown, row: Record<string, unknown>) => unknown;
    }>;
    data: Record<string, unknown>[];
    selectable?: boolean;
    selectedIds?: Set<string>;
  } = $props();
  
  let sortKey = $state<string | null>(null);
  let sortDirection = $state<'asc' | 'desc'>('asc');

  function handleSort(key: string) {
    if (sortKey === key) {
      sortDirection = sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      sortKey = key;
      sortDirection = 'asc';
    }
  }

  function toggleSelectAll() {
    if (!selectable) return;
    const newSet = new Set<string>();
    if (selectedIds.size !== data.length) {
      data.forEach(row => {
        newSet.add(row.id as string);
      });
    }
    selectedIds = newSet;
  }

  function toggleSelect(id: string) {
    if (!selectable) return;
    const newSet = new Set(selectedIds);
    if (newSet.has(id)) {
      newSet.delete(id);
    } else {
      newSet.add(id);
    }
    selectedIds = newSet;
  }

  let sortedData = $derived([...data].sort((a, b) => {
    if (!sortKey) return 0;
    const aVal = a[sortKey];
    const bVal = b[sortKey];
    
    if (typeof aVal === 'number' && typeof bVal === 'number') {
      return sortDirection === 'asc' ? aVal - bVal : bVal - aVal;
    }
    
    const aStr = String(aVal ?? '');
    const bStr = String(bVal ?? '');
    return sortDirection === 'asc' 
      ? aStr.localeCompare(bStr) 
      : bStr.localeCompare(aStr);
  }));
</script>

<div class="overflow-x-auto">
  <table class="w-full border-collapse">
    <thead>
      <tr class="bg-dark-700" style="opacity: 0.5;">
        {#if selectable}
          <th class="px-4 py-3 text-left">
            <input 
              type="checkbox"
              checked={selectedIds.size === data.length && data.length > 0}
              onchange={toggleSelectAll}
              class="w-4 h-4 rounded border-dark-500 bg-dark-800 text-aviation-600 focus:ring-aviation-500"
            />
          </th>
        {/if}
        {#each columns as col}
          <th 
            class="px-4 py-3 text-left hud-text whitespace-nowrap"
            style={col.width ? `width: ${col.width}` : ''}
          >
            <div 
              class="flex items-center gap-1"
              class:cursor-pointer={col.sortable}
              onclick={col.sortable ? () => handleSort(col.key) : undefined}
            >
              {col.label}
              {#if col.sortable}
                <span class="text-gray-500">
                  {#if sortKey === col.key}
                    {#if sortDirection === 'asc'}
                      <ChevronUp class="w-4 h-4" />
                    {:else}
                      <ChevronDown class="w-4 h-4" />
                    {/if}
                  {/if}
                </span>
              {/if}
            </div>
          </th>
        {/each}
      </tr>
    </thead>
    <tbody class="divide-y divide-dark-600">
      {#each sortedData as row (row.id)}
        <tr 
          class="transition-colors"
          style={selectable && selectedIds.has(row.id as string) ? 'background: rgba(10, 37, 64, 0.3)' : ''}
          onmouseenter={(e) => (e.currentTarget.style.background = 'rgba(37, 37, 66, 0.3)')}
          onmouseleave={(e) => (e.currentTarget.style.background = selectable && selectedIds.has(row.id as string) ? 'rgba(10, 37, 64, 0.3)' : '')}
        >
          {#if selectable}
            <td class="px-4 py-3">
              <input 
                type="checkbox"
                checked={selectedIds.has(row.id as string)}
                onchange={() => toggleSelect(row.id as string)}
                onclick={(e) => e.stopPropagation()}
                class="w-4 h-4 rounded border-dark-500 bg-dark-800 text-aviation-600 focus:ring-aviation-500"
              />
            </td>
          {/if}
          {#each columns as col}
            <td class="px-4 py-3 text-sm text-gray-300">
              {#if col.render}
                {@const value = col.render(row[col.key], row)}
                {#if typeof value === 'string'}
                  {value}
                {:else}
                  {@html value as string}
                {/if}
              {:else}
                {row[col.key]}
              {/if}
            </td>
          {/each}
        </tr>
      {/each}
      {#if data.length === 0}
        <tr>
          <td 
            colspan={columns.length + (selectable ? 1 : 0)} 
            class="px-4 py-12 text-center text-gray-500"
          >
            暂无数据
          </td>
        </tr>
      {/if}
    </tbody>
  </table>
</div>

// StackMatrixs/src/components/common/DataTable.tsx
import React from 'react';
import { classNames } from '@/utils/formatters';

interface DataTableColumn<T> {
  key: keyof T | string;
  label: string;
  render?: (row: T) => React.ReactNode;
  width?: string;
  align?: 'left' | 'center' | 'right';
  sortable?: boolean;
}

interface DataTableProps<T> {
  columns: DataTableColumn<T>[];
  data: T[];
  loading?: boolean;
  emptyText?: string;
  className?: string;
  rowClassName?: string | ((row: T) => string);
  onRowClick?: (row: T) => void;
}

export function DataTable<T extends { id?: string }>({
  columns,
  data,
  loading = false,
  emptyText = '暂无数据',
  className = '',
  rowClassName = '',
  onRowClick,
}: DataTableProps<T>) {
  return (
    <div className={classNames('overflow-x-auto wms-scrollbar', className)}>
      <table className="w-full">
        <thead>
          <tr className="border-b border-wms-border">
            {columns.map((col) => (
              <th
                key={String(col.key)}
                className={classNames(
                  'px-4 py-3 text-left text-xs font-medium text-wms-subtext uppercase tracking-wider',
                  col.align === 'center' && 'text-center',
                  col.align === 'right' && 'text-right',
                  col.width && `w-${col.width}`
                )}
              >
                {col.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-wms-border/50">
          {loading ? (
            <tr>
              <td colSpan={columns.length} className="px-4 py-12 text-center">
                <div className="flex items-center justify-center gap-2 text-wms-subtext">
                  <div className="w-4 h-4 border-2 border-wms-primary border-t-transparent rounded-full animate-spin" />
                  加载中...
                </div>
              </td>
            </tr>
          ) : data.length === 0 ? (
            <tr>
              <td colSpan={columns.length} className="px-4 py-12 text-center text-wms-subtext">
                {emptyText}
              </td>
            </tr>
          ) : (
            data.map((row, idx) => (
              <tr
                key={row.id || idx}
                className={classNames(
                  'transition-colors hover:bg-wms-bg/50',
                  onRowClick && 'cursor-pointer',
                  typeof rowClassName === 'function' ? rowClassName(row) : rowClassName
                )}
                onClick={() => onRowClick?.(row)}
              >
                {columns.map((col) => (
                  <td
                    key={String(col.key)}
                    className={classNames(
                      'px-4 py-3 text-sm text-wms-text',
                      col.align === 'center' && 'text-center',
                      col.align === 'right' && 'text-right'
                    )}
                  >
                    {col.render
                      ? col.render(row)
                      : (row[col.key as keyof T] as React.ReactNode)}
                  </td>
                ))}
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  );
}
