// StackMatrix/src/components/Layout/Header.tsx
import { Bell, Search, User, RefreshCw } from 'lucide-react';
import { motion } from 'framer-motion';
import { useEffect, useState } from 'react';
import useWMSStore from '../../store/useWMSStore';

interface HeaderProps {
  title: string;
  subtitle?: string;
}

export default function Header({ title, subtitle }: HeaderProps) {
  const [currentTime, setCurrentTime] = useState(new Date());
  const { metrics, refreshMetrics } = useWMSStore();

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const formatTime = (date: Date) => {
    return date.toLocaleTimeString('zh-CN', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false
    });
  };

  const formatDate = (date: Date) => {
    return date.toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      weekday: 'short'
    });
  };

  return (
    <motion.header
      initial={{ y: -80, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className="h-16 bg-surface/80 backdrop-blur-md border-b border-surface-border sticky top-0 z-40"
    >
      <div className="h-full px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div>
            <h1 className="text-xl font-bold text-text-primary">{title}</h1>
            {subtitle && (
              <p className="text-sm text-text-muted">{subtitle}</p>
            )}
          </div>
        </div>

        <div className="flex items-center gap-6">
          <div className="hidden md:flex items-center gap-2 bg-background rounded-lg px-4 py-2">
            <Search className="w-4 h-4 text-text-muted" />
            <input
              type="text"
              placeholder="搜索 SKU、货位..."
              className="bg-transparent border-none outline-none text-sm text-text-primary placeholder:text-text-muted w-48"
            />
          </div>

          <div className="flex items-center gap-4">
            <div className="text-right hidden lg:block">
              <p className="text-sm font-mono text-primary">{formatTime(currentTime)}</p>
              <p className="text-xs text-text-muted">{formatDate(currentTime)}</p>
            </div>

            <div className="h-8 w-px bg-surface-border" />

            <motion.button
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.95 }}
              onClick={refreshMetrics}
              className="relative p-2 rounded-lg hover:bg-surface-hover transition-colors"
            >
              <RefreshCw className="w-5 h-5 text-text-secondary" />
            </motion.button>

            <motion.button
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.95 }}
              className="relative p-2 rounded-lg hover:bg-surface-hover transition-colors"
            >
              <Bell className="w-5 h-5 text-text-secondary" />
              <span className="absolute top-1 right-1 w-2 h-2 bg-accent-red rounded-full animate-pulse" />
            </motion.button>

            <div className="flex items-center gap-3 pl-2 border-l border-surface-border">
              <div className="w-9 h-9 bg-gradient-to-br from-primary to-primary-dark rounded-full flex items-center justify-center">
                <User className="w-5 h-5 text-white" />
              </div>
              <div className="hidden sm:block">
                <p className="text-sm font-medium text-text-primary">管理员</p>
                <p className="text-xs text-text-muted">仓储管理</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="h-px bg-gradient-to-r from-transparent via-primary/30 to-transparent" />
    </motion.header>
  );
}

// MoldNexus/src/components/layout/Header.tsx
import { Component } from 'solid-js';
import { Bell, Search, User, Database } from 'lucide-solid';
import { useAppStore } from '@/stores/appStore';

const Header: Component = () => {
  const { state } = useAppStore();

  return (
    <header class="h-14 bg-dark-200 border-b border-dark-100 flex items-center justify-between px-4 z-50 sticky top-0">
      <div class="flex items-center gap-4">
        <div class="flex items-center gap-2">
          <div class="w-8 h-8 bg-gradient-to-br from-primary-500 to-accent-cyan rounded-lg flex items-center justify-center">
            <Database class="w-5 h-5 text-white" />
          </div>
          <span class="text-lg font-bold bg-gradient-to-r from-primary-400 to-accent-cyan bg-clip-text text-transparent">
            MoldNexus
          </span>
        </div>

        <div class="hidden md:flex items-center gap-2 ml-8">
          <div class="relative">
            <Search class="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" />
            <input
              type="text"
              placeholder="搜索模拟任务、参数..."
              class="w-72 pl-10 pr-4 py-1.5 bg-dark-100 border border-dark-100 rounded-lg text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-primary-500 transition-colors"
            />
          </div>
        </div>
      </div>

      <div class="flex items-center gap-3">
        <div class={`flex items-center gap-2 px-2 py-1 rounded ${
          state.dbReady ? 'bg-accent-green/20 text-accent-green' : 'bg-accent-yellow/20 text-accent-yellow'
        }`}>
          <div class={`w-2 h-2 rounded-full ${state.dbReady ? 'bg-accent-green' : 'bg-accent-yellow animate-pulse'}`} />
          <span class="text-xs font-medium">
            {state.dbReady ? '数据库已连接' : '连接中...'}
          </span>
        </div>

        <button class="relative p-2 text-gray-400 hover:text-gray-200 hover:bg-dark-100 rounded-lg transition-colors">
          <Bell class="w-5 h-5" />
          <span class="absolute top-1 right-1 w-2 h-2 bg-accent-red rounded-full" />
        </button>

        <div class="flex items-center gap-3 pl-3 border-l border-dark-100">
          <div class="w-8 h-8 bg-primary-600 rounded-full flex items-center justify-center">
            <User class="w-4 h-4 text-white" />
          </div>
          <div class="hidden md:block">
            <p class="text-sm font-medium text-gray-200">{state.currentUser?.name}</p>
            <p class="text-xs text-gray-500">
              {state.currentUser?.role === 'process_engineer' && '工艺工程师'}
              {state.currentUser?.role === 'production_operator' && '生产线操作员'}
              {state.currentUser?.role === 'quality_engineer' && '质量工程师'}
              {state.currentUser?.role === 'admin' && '系统管理员'}
            </p>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
