// GrindLogic/components/Header.tsx
'use client';

import { motion } from 'framer-motion';
import { Bell, Search, User, Wifi, WifiOff } from 'lucide-react';
import { useAppStore } from '@/store';

export function Header() {
  const { isConnected, currentPart, currentBatch } = useAppStore();

  return (
    <motion.header
      initial={{ y: -100, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className="fixed top-0 right-0 left-72 h-16 bg-dark-800/80 backdrop-blur-xl border-b border-dark-700/50 z-30 flex items-center justify-between px-6"
    >
      <div className="flex items-center gap-6">
        <div>
          <h2 className="text-lg font-semibold text-white">当前加工</h2>
          <div className="flex items-center gap-4 text-xs text-dark-400">
            <span>零件: {currentPart}</span>
            <span>批次: {currentBatch}</span>
          </div>
        </div>
      </div>

      <div className="flex items-center gap-4">
        <div className="relative">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-dark-500" />
          <input
            type="text"
            placeholder="搜索零件、批次..."
            className="w-64 pl-9 pr-4 py-2 bg-dark-700/50 border border-dark-600/50 rounded-lg text-sm text-dark-200 placeholder-dark-500 focus:outline-none focus:border-primary-500/50 focus:ring-1 focus:ring-primary-500/30 transition-all"
          />
        </div>

        <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-dark-700/50">
          {isConnected ? (
            <Wifi className="w-4 h-4 text-accent-400" />
          ) : (
            <WifiOff className="w-4 h-4 text-warning-400" />
          )}
          <span className={`text-xs font-medium ${isConnected ? 'text-accent-400' : 'text-warning-400'}`}>
            {isConnected ? '已连接' : '断开连接'}
          </span>
        </div>

        <button className="relative p-2 rounded-lg hover:bg-dark-700/50 transition-colors">
          <Bell className="w-5 h-5 text-dark-300" />
          <span className="absolute top-1 right-1 w-2 h-2 bg-warning-400 rounded-full" />
        </button>

        <div className="flex items-center gap-3 pl-4 border-l border-dark-700">
          <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center">
            <User className="w-4 h-4 text-white" />
          </div>
          <div className="hidden sm:block">
            <div className="text-sm font-medium text-white">工程师</div>
            <div className="text-xs text-dark-500">工艺管理员</div>
          </div>
        </div>
      </div>
    </motion.header>
  );
}

// MoldNexus/src/components/layout/Header.tsx
import { Component } from 'solid-js';
import { Bell, Search, User, Database } from 'lucide-solid';
import { useAppStore } from '@/stores/appStore';

const Header: Component = () => {
  const { state } = useAppStore();

  return (
    <header class="h-14 bg-dark-200 border-b border-dark-100 flex items-center justify-between px-4 z-50 sticky top-0">
      <div class="flex items-center gap-4">
        <div class="flex items-center gap-2">
          <div class="w-8 h-8 bg-gradient-to-br from-primary-500 to-accent-cyan rounded-lg flex items-center justify-center">
            <Database class="w-5 h-5 text-white" />
          </div>
          <span class="text-lg font-bold bg-gradient-to-r from-primary-400 to-accent-cyan bg-clip-text text-transparent">
            MoldNexus
          </span>
        </div>

        <div class="hidden md:flex items-center gap-2 ml-8">
          <div class="relative">
            <Search class="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" />
            <input
              type="text"
              placeholder="搜索模拟任务、参数..."
              class="w-72 pl-10 pr-4 py-1.5 bg-dark-100 border border-dark-100 rounded-lg text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-primary-500 transition-colors"
            />
          </div>
        </div>
      </div>

      <div class="flex items-center gap-3">
        <div class={`flex items-center gap-2 px-2 py-1 rounded ${
          state.dbReady ? 'bg-accent-green/20 text-accent-green' : 'bg-accent-yellow/20 text-accent-yellow'
        }`}>
          <div class={`w-2 h-2 rounded-full ${state.dbReady ? 'bg-accent-green' : 'bg-accent-yellow animate-pulse'}`} />
          <span class="text-xs font-medium">
            {state.dbReady ? '数据库已连接' : '连接中...'}
          </span>
        </div>

        <button class="relative p-2 text-gray-400 hover:text-gray-200 hover:bg-dark-100 rounded-lg transition-colors">
          <Bell class="w-5 h-5" />
          <span class="absolute top-1 right-1 w-2 h-2 bg-accent-red rounded-full" />
        </button>

        <div class="flex items-center gap-3 pl-3 border-l border-dark-100">
          <div class="w-8 h-8 bg-primary-600 rounded-full flex items-center justify-center">
            <User class="w-4 h-4 text-white" />
          </div>
          <div class="hidden md:block">
            <p class="text-sm font-medium text-gray-200">{state.currentUser?.name}</p>
            <p class="text-xs text-gray-500">
              {state.currentUser?.role === 'process_engineer' && '工艺工程师'}
              {state.currentUser?.role === 'production_operator' && '生产线操作员'}
              {state.currentUser?.role === 'quality_engineer' && '质量工程师'}
              {state.currentUser?.role === 'admin' && '系统管理员'}
            </p>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
