// AirCargoNexust/src/components/Sidebar.svelte
<script lang="ts">
  import Link from '@/router/Link.svelte';
  import { currentRoute } from '@/router';
  import { 
    Box, 
    Package, 
    Calculator, 
    Camera, 
    Settings, 
    PlaneTakeoff,
    ChevronRight
  } from 'lucide-svelte';

  let isCollapsed = $state(false);

  const navItems = [
    { path: '/', icon: Box, label: '货舱可视化' },
    { path: '/cargo', icon: Package, label: '货物管理' },
    { path: '/calculate', icon: Calculator, label: '配载计算' },
    { path: '/snapshots', icon: Camera, label: '配载快照' },
    { path: '/cockpit', icon: PlaneTakeoff, label: '机组终端' }
  ];
</script>

<aside 
  class="h-full flex flex-col bg-dark-800 border-r border-dark-600 transition-all duration-300"
  class:is-collapsed={isCollapsed}
  style="width: {isCollapsed ? '64px' : '240px'}"
>
  <div class="p-4 border-b border-dark-600 flex items-center justify-between">
    <div class="flex items-center gap-3 overflow-hidden">
      <div class="w-10 h-10 rounded-lg bg-aviation-700 flex items-center justify-center flex-shrink-0">
        <PlaneTakeoff class="w-6 h-6 text-white" />
      </div>
      {#if !isCollapsed}
        <div class="whitespace-nowrap">
          <div class="font-display font-bold text-white text-lg leading-tight">AirCargo</div>
          <div class="text-xs text-gray-400">Nexus v1.0</div>
        </div>
      {/if}
    </div>
    <button 
      onclick={() => isCollapsed = !isCollapsed}
      class="p-1 hover:bg-dark-600 rounded transition-colors flex-shrink-0"
    >
      <ChevronRight 
        class="w-5 h-5 text-gray-400 transition-transform"
        style="transform: rotate({isCollapsed ? '0deg' : '180deg'})"
      />
    </button>
  </div>

  <nav class="flex-1 py-4 overflow-y-auto">
    <ul class="space-y-1 px-2">
      {#each navItems as item}
        <li>
          <Link 
            to={item.path}
            class={`flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 ${
              $currentRoute === item.path
                ? 'bg-aviation-700 text-white' 
                : 'text-gray-400 hover:text-white hover:bg-dark-700'
            }`}
          >
            {#if $currentRoute === item.path}
              <div class="absolute left-0 top-0 bottom-0 w-1 bg-aviation-500 rounded-r"></div>
            {/if}
            <svelte:component this={item.icon} class="w-5 h-5 flex-shrink-0" />
            {#if !isCollapsed}
              <span class="text-sm whitespace-nowrap">{item.label}</span>
            {/if}
          </Link>
        </li>
      {/each}
    </ul>
  </nav>

  <div class="p-4 border-t border-dark-600">
    <button 
      class="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-400 hover:text-white hover:bg-dark-700 transition-colors"
    >
      <Settings class="w-5 h-5 flex-shrink-0" />
      {#if !isCollapsed}
        <span class="text-sm whitespace-nowrap">系统设置</span>
      {/if}
    </button>
  </div>
</aside>

// MoldNexus/src/components/layout/Sidebar.tsx
import { Component } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import {
  LayoutDashboard,
  Beaker,
  Database,
  ArrowRightLeft,
  Users,
  BarChart3,
  Settings,
  ChevronLeft,
  ChevronRight,
} from 'lucide-solid';
import { useAppStore } from '@/stores/appStore';

const menuItems = [
  { path: '/', icon: LayoutDashboard, label: '仪表盘' },
  { path: '/simulation', icon: Beaker, label: '模拟工作台' },
  { path: '/parameters', icon: Database, label: '参数管理' },
  { path: '/mapping', icon: ArrowRightLeft, label: '语义映射' },
  { path: '/collaboration', icon: Users, label: '协作中心' },
  { path: '/analytics', icon: BarChart3, label: '分析报告' },
  { path: '/settings', icon: Settings, label: '系统设置' },
];

const Sidebar: Component = () => {
  const location = useLocation();
  const { state, toggleSidebar } = useAppStore();

  return (
    <aside
      class={`fixed left-0 top-14 bottom-0 bg-dark-200 border-r border-dark-100 transition-all duration-300 z-40 ${
        state.sidebarCollapsed ? 'w-16' : 'w-64'
      }`}
    >
      <div class="flex flex-col h-full">
        <nav class="flex-1 py-4">
          <ul class="space-y-1 px-2">
            {menuItems.map((item) => {
              const isActive = location.pathname === item.path;
              return (
                <li>
                  <A
                    href={item.path}
                    class={`flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 ${
                      isActive
                        ? 'bg-primary-600 text-white shadow-lg shadow-primary-600/30'
                        : 'text-gray-400 hover:bg-dark-100 hover:text-gray-200'
                    }`}
                  >
                    <item.icon class="w-5 h-5 flex-shrink-0" />
                    {!state.sidebarCollapsed && (
                      <span class="text-sm font-medium">{item.label}</span>
                    )}
                  </A>
                </li>
              );
            })}
          </ul>
        </nav>

        <button
          onClick={toggleSidebar}
          class="p-3 border-t border-dark-100 text-gray-400 hover:text-gray-200 hover:bg-dark-100 transition-colors flex items-center justify-center"
        >
          {state.sidebarCollapsed ? (
            <ChevronRight class="w-5 h-5" />
          ) : (
            <ChevronLeft class="w-5 h-5" />
          )}
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;
