// CrainPulse/src/components/AlertPanel.tsx
import { For } from 'solid-js';
import type { WarningAlert, CollisionRisk } from '../types/crane';

interface AlertPanelProps {
  alerts: WarningAlert[];
  collisionRisks: CollisionRisk[];
  onAcknowledge: (id: string) => void;
}

export function AlertPanel(props: AlertPanelProps) {
  const unacknowledgedAlerts = () => props.alerts.filter(a => !a.acknowledged);

  const riskLevelColors = {
    low: 'bg-blue-100 text-blue-800 border-blue-300',
    medium: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    high: 'bg-orange-100 text-orange-800 border-orange-300',
    critical: 'bg-red-100 text-red-800 border-red-300'
  };

  const alertLevelColors = {
    warning: 'bg-yellow-500',
    danger: 'bg-orange-500',
    emergency: 'bg-red-600 animate-pulse'
  };

  return (
    <div class="alert-panel space-y-4">
      <div class="bg-white rounded-lg shadow p-4">
        <h3 class="text-lg font-semibold mb-3 text-gray-800">碰撞风险预警</h3>
        <div class="space-y-2">
          <For each={props.collisionRisks}>
            {(risk) => (
              <div class={`p-3 rounded-lg border ${riskLevelColors[risk.riskLevel]}`}>
                <div class="flex justify-between items-start">
                  <div>
                    <span class="font-medium">
                      {risk.craneA} ↔ {risk.craneB}
                    </span>
                    <p class="text-sm mt-1 opacity-80">
                      距离: {risk.distance.toFixed(1)}m | 
                      预测: {Math.max(0, Math.round(risk.predictedTime / 1000))}s
                    </p>
                    <p class="text-xs mt-1 opacity-70">
                      动能: {(risk.kineticEnergyA + risk.kineticEnergyB).toFixed(0)}J
                    </p>
                  </div>
                  <span class="px-2 py-1 rounded text-xs font-medium bg-white bg-opacity-50">
                    {risk.riskLevel === 'critical' ? '紧急' : 
                     risk.riskLevel === 'high' ? '高危' :
                     risk.riskLevel === 'medium' ? '中危' : '低危'}
                  </span>
                </div>
              </div>
            )}
          </For>
          {props.collisionRisks.length === 0 && (
            <div class="text-center py-4 text-gray-500">
              ✅ 暂无碰撞风险
            </div>
          )}
        </div>
      </div>

      <div class="bg-white rounded-lg shadow p-4">
        <div class="flex justify-between items-center mb-3">
          <h3 class="text-lg font-semibold text-gray-800">警报通知</h3>
          <span class={`px-2 py-1 rounded text-white text-sm ${alertLevelColors[unacknowledgedAlerts().length > 0 ? 'emergency' : 'warning']}`}>
            {unacknowledgedAlerts().length} 条未处理
          </span>
        </div>
        <div class="space-y-2 max-h-60 overflow-y-auto">
          <For each={unacknowledgedAlerts()}>
            {(alert) => (
              <div class={`p-3 rounded-lg border ${
                alert.level === 'emergency' ? 'bg-red-50 border-red-300' :
                alert.level === 'danger' ? 'bg-orange-50 border-orange-300' :
                'bg-yellow-50 border-yellow-300'
              }`}>
                <div class="flex justify-between items-start">
                  <div class="flex-1">
                    <div class="flex items-center gap-2">
                      <span class={`w-2 h-2 rounded-full ${
                        alert.level === 'emergency' ? 'bg-red-500 animate-ping' :
                        alert.level === 'danger' ? 'bg-orange-500' : 'bg-yellow-500'
                      }`}></span>
                      <span class="font-medium text-sm">{alert.craneId}</span>
                    </div>
                    <p class="text-sm mt-1 text-gray-700">{alert.message}</p>
                    <p class="text-xs mt-1 text-gray-500">
                      {new Date(alert.timestamp).toLocaleTimeString()}
                    </p>
                  </div>
                  <button
                    onClick={() => props.onAcknowledge(alert.id)}
                    class="ml-2 px-3 py-1 bg-white border rounded text-sm hover:bg-gray-50 transition-colors"
                  >
                    确认
                  </button>
                </div>
              </div>
            )}
          </For>
          {unacknowledgedAlerts().length === 0 && (
            <div class="text-center py-4 text-gray-500">
              ✅ 暂无警报
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// RailLogic/src/components/AlertPanel.svelte
<script lang="ts">
  import { alerts, unacknowledgedAlerts } from '../lib/stores';
  import type { Alert } from '../types';

  let allAlerts = $state<Alert[]>([]);
  let unacknowledged = $state<Alert[]>([]);

  $effect(() => {
    const unsub1 = alerts.subscribe((a) => {
      allAlerts = a;
    });
    const unsub2 = unacknowledgedAlerts.subscribe((a) => {
      unacknowledged = a;
    });
    return () => {
      unsub1();
      unsub2();
    };
  });

  function formatTime(timestamp: number): string {
    return new Date(timestamp).toLocaleTimeString('zh-CN');
  }

  function getLevelColor(level: Alert['level']): string {
    switch (level) {
      case 'emergency': return 'bg-red-600';
      case 'critical': return 'bg-red-500';
      case 'warning': return 'bg-yellow-500';
      default: return 'bg-blue-500';
    }
  }

  function getLevelText(level: Alert['level']): string {
    switch (level) {
      case 'emergency': return '紧急';
      case 'critical': return '严重';
      case 'warning': return '警告';
      default: return '信息';
    }
  }

  function getSourceText(source: Alert['source']): string {
    switch (source) {
      case 'pantograph': return '受电弓';
      case 'track': return '轨道';
      case 'trajectory': return '轨迹';
      default: return '系统';
    }
  }

  function acknowledgeAlert(id: string): void {
    alerts.acknowledge(id);
  }
</script>

<div class="p-4 bg-gray-900 rounded-lg shadow-lg">
  <h3 class="text-xl font-bold text-white mb-4 flex items-center gap-2">
    <span class="text-2xl">⚠️</span>
    告警中心
    {#if unacknowledged.length > 0}
      <span class="bg-red-500 text-white text-sm px-2 py-0.5 rounded-full animate-pulse">
        {unacknowledged.length}
      </span>
    {/if}
  </h3>

  {#if allAlerts.length === 0}
    <div class="text-gray-400 text-center py-8">
      暂无告警
    </div>
  {:else}
    <div class="space-y-2 max-h-80 overflow-y-auto">
      {#each allAlerts.slice(0, 20) as alert (alert.id)}
        <div
          class="p-3 rounded-lg border-l-4 {alert.acknowledged ? 'bg-gray-800 opacity-60' : 'bg-gray-800'}"
          class:border-red-500={alert.level === 'critical' || alert.level === 'emergency'}
          class:border-yellow-500={alert.level === 'warning'}
          class:border-blue-500={alert.level === 'info'}
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-2 mb-1">
                <span class="text-xs px-2 py-0.5 rounded text-white {getLevelColor(alert.level)}">
                  {getLevelText(alert.level)}
                </span>
                <span class="text-xs text-gray-400">{getSourceText(alert.source)}</span>
                <span class="text-xs text-gray-500">{formatTime(alert.timestamp)}</span>
              </div>
              <p class="text-white text-sm">{alert.message}</p>
              {#if alert.trainId || alert.mileage}
                <div class="text-xs text-gray-400 mt-1">
                  {#if alert.trainId}列车: {alert.trainId}{/if}
                  {#if alert.trainId && alert.mileage} | {/if}
                  {#if alert.mileage}里程: K{(alert.mileage / 1000).toFixed(3)}{/if}
                </div>
              {/if}
            </div>
            {#if !alert.acknowledged}
              <button
                class="ml-2 text-xs text-gray-400 hover:text-white px-2 py-1 rounded hover:bg-gray-700"
                onclick={() => acknowledgeAlert(alert.id)}
              >
                确认
              </button>
            {/if}
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>
