// TankNexust/src/components/common/StatusIndicator.vue
<script setup lang="ts">
interface Props {
  status: 'normal' | 'warning' | 'danger' | 'critical' | 'offline'
  label?: string
  showLabel?: boolean
  size?: 'sm' | 'md' | 'lg'
}

const props = withDefaults(defineProps<Props>(), {
  showLabel: true,
  size: 'md'
})

const statusConfig = {
  normal: { color: 'bg-risk-safe', label: '正常', pulse: false },
  warning: { color: 'bg-risk-caution', label: '警告', pulse: true },
  danger: { color: 'bg-risk-warning', label: '危险', pulse: true },
  critical: { color: 'bg-risk-danger', label: '危急', pulse: true },
  offline: { color: 'bg-text-muted', label: '离线', pulse: false }
}

const sizeClasses = {
  sm: 'w-2 h-2',
  md: 'w-3 h-3',
  lg: 'w-4 h-4'
}
</script>

<template>
  <div class="flex items-center gap-2">
    <span
      class="rounded-full"
      :class="[
        sizeClasses[size],
        statusConfig[status].color,
        statusConfig[status].pulse ? 'animate-pulse' : ''
      ]"
    ></span>
    <span v-if="showLabel && label" class="text-sm">{{ label }}</span>
    <span v-if="showLabel && !label" class="text-sm">{{ statusConfig[status].label }}</span>
  </div>
</template>

// NetPulse/src/components/ui/StatusIndicator.tsx
import { Component } from 'solid-js';

interface StatusIndicatorProps {
  status: 'online' | 'offline' | 'maintenance' | 'warning' | 'critical';
  size?: 'sm' | 'md' | 'lg';
  showLabel?: boolean;
}

const statusColors: Record<string, string> = {
  online: 'bg-alert-green',
  offline: 'bg-metal-700',
  maintenance: 'bg-alert-orange',
  warning: 'bg-alert-orange',
  critical: 'bg-alert-red',
};

const statusLabels: Record<string, string> = {
  online: '在线',
  offline: '离线',
  maintenance: '维护',
  warning: '警告',
  critical: '严重',
};

const sizeClasses: Record<string, string> = {
  sm: 'w-2 h-2',
  md: 'w-3 h-3',
  lg: 'w-4 h-4',
};

export const StatusIndicator: Component<StatusIndicatorProps> = (props) => {
  const size = () => props.size || 'md';

  return (
    <div class="flex items-center gap-2">
      <div
        class={`status-indicator ${sizeClasses[size()]} ${statusColors[props.status]} after:${statusColors[props.status]}`}
      />
      {props.showLabel && (
        <span class="text-sm text-metal-300">{statusLabels[props.status]}</span>
      )}
    </div>
  );
};
