// CableLink/src/components/common/StatCard.svelte
<script lang="ts">
  let { label, value, unit = '', color = '#3E92CC', trend, icon } = $props<{
    label: string;
    value: number | string;
    unit?: string;
    color?: string;
    trend?: { value: number; isPositive: boolean };
    icon?: string;
  }>();
</script>

<div class="panel-glow p-5 relative overflow-hidden group hover:scale-[1.02] transition-transform duration-300">
  <div class="absolute top-0 left-0 w-full h-1 opacity-80" style="background: linear-gradient(90deg, {color}, transparent)"></div>

  <div class="flex items-start justify-between">
    <div>
      <p class="stat-label mb-2">{label}</p>
      <div class="flex items-baseline gap-1">
        <span class="stat-value" style="color: {color}">
          {typeof value === 'number' ? value.toLocaleString('zh-CN', { maximumFractionDigits: 1 }) : value}
        </span>
        {#if unit}
          <span class="text-sm text-gray-400">{unit}</span>
        {/if}
      </div>
      {#if trend}
        <div class="flex items-center gap-1 mt-2 text-xs">
          <span class={trend.isPositive ? 'text-safe-green' : 'text-danger-red'}>
            {trend.isPositive ? '↑' : '↓'} {Math.abs(trend.value).toFixed(1)}%
          </span>
          <span class="text-gray-500">较上周期</span>
        </div>
      {/if}
    </div>
    {#if icon}
      <div
        class="w-12 h-12 rounded-xl flex items-center justify-center text-2xl opacity-50 group-hover:opacity-100 transition-opacity"
        style="background: {color}20"
      >
        {icon}
      </div>
    {/if}
  </div>

  <div class="absolute -bottom-10 -right-10 w-32 h-32 rounded-full opacity-5 group-hover:opacity-10 transition-opacity" style="background: {color}"></div>
</div>

// VertiPulset/src/components/ui/StatCard.tsx
import { cn } from '@/utils/format';

interface StatCardProps {
  label: string;
  value: string | number;
  unit?: string;
  trend?: number;
  status?: 'normal' | 'warning' | 'error';
  icon?: React.ReactNode;
  className?: string;
}

export function StatCard({ label, value, unit, trend, status = 'normal', icon, className }: StatCardProps) {
  const statusColors = {
    normal: 'text-status-green',
    warning: 'text-alert-orange',
    error: 'text-red-500'
  };

  return (
    <div className={cn(
      'glass-card p-4 relative overflow-hidden',
      className
    )}>
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-electric-blue/0 via-electric-blue to-electric-blue/0"></div>
      
      <div className="flex items-start justify-between">
        <div>
          <p className="text-xs text-metal-gray mb-1">{label}</p>
          <div className="flex items-baseline gap-1">
            <span className={cn(
              'text-2xl font-bold font-display',
              statusColors[status]
            )}>
              {value}
            </span>
            {unit && <span className="text-xs text-metal-gray">{unit}</span>}
          </div>
          {trend !== undefined && (
            <div className={cn(
              'text-xs mt-1 flex items-center gap-1',
              trend >= 0 ? 'text-status-green' : 'text-alert-orange'
            )}>
              <span>{trend >= 0 ? '↑' : '↓'}</span>
              <span>{Math.abs(trend)}%</span>
            </div>
          )}
        </div>
        {icon && (
          <div className="p-2 rounded-lg bg-electric-blue/10 text-electric-blue">
            {icon}
          </div>
        )}
      </div>
    </div>
  );
}
