// AirCargoNexust/src/components/StatCard.svelte
<script lang="ts">
  let {
    label,
    value,
    unit = '',
    trend,
    status = 'normal' as 'normal' | 'warning' | 'danger'
  }: {
    label: string;
    value: string | number;
    unit?: string;
    trend?: number;
    status?: 'normal' | 'warning' | 'danger';
  } = $props();
</script>

<div class="glass-panel p-4">
  <div class="hud-text mb-1">{label}</div>
  <div class="flex items-baseline gap-1">
    <span 
      class="font-display text-2xl font-bold"
      class:text-alert-green={status === 'normal'}
      class:text-alert-orange={status === 'warning'}
      class:text-alert-red={status === 'danger'}
    >
      {value}
    </span>
    {#if unit}
      <span class="text-sm text-gray-400">{unit}</span>
    {/if}
  </div>
  {#if trend !== undefined}
    <div class="mt-2 text-xs">
      <span 
        class={trend >= 0 ? 'text-alert-green' : 'text-alert-red'}
      >
        {trend >= 0 ? '↑' : '↓'} {Math.abs(trend).toFixed(1)}%
      </span>
      <span class="text-gray-500 ml-1">vs 基准</span>
    </div>
  {/if}
</div>

// VertiPulset/src/components/ui/StatCard.tsx
import { cn } from '@/utils/format';

interface StatCardProps {
  label: string;
  value: string | number;
  unit?: string;
  trend?: number;
  status?: 'normal' | 'warning' | 'error';
  icon?: React.ReactNode;
  className?: string;
}

export function StatCard({ label, value, unit, trend, status = 'normal', icon, className }: StatCardProps) {
  const statusColors = {
    normal: 'text-status-green',
    warning: 'text-alert-orange',
    error: 'text-red-500'
  };

  return (
    <div className={cn(
      'glass-card p-4 relative overflow-hidden',
      className
    )}>
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-electric-blue/0 via-electric-blue to-electric-blue/0"></div>
      
      <div className="flex items-start justify-between">
        <div>
          <p className="text-xs text-metal-gray mb-1">{label}</p>
          <div className="flex items-baseline gap-1">
            <span className={cn(
              'text-2xl font-bold font-display',
              statusColors[status]
            )}>
              {value}
            </span>
            {unit && <span className="text-xs text-metal-gray">{unit}</span>}
          </div>
          {trend !== undefined && (
            <div className={cn(
              'text-xs mt-1 flex items-center gap-1',
              trend >= 0 ? 'text-status-green' : 'text-alert-orange'
            )}>
              <span>{trend >= 0 ? '↑' : '↓'}</span>
              <span>{Math.abs(trend)}%</span>
            </div>
          )}
        </div>
        {icon && (
          <div className="p-2 rounded-lg bg-electric-blue/10 text-electric-blue">
            {icon}
          </div>
        )}
      </div>
    </div>
  );
}
