// HeliLink/src/components/GaugeMeter.tsx
import React from 'react';
import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';

interface GaugeMeterProps {
  value: number;
  max: number;
  min?: number;
  label: string;
  unit?: string;
  size?: 'sm' | 'md' | 'lg';
  segments?: { threshold: number; color: string }[];
  showValue?: boolean;
}

export const GaugeMeter: React.FC<GaugeMeterProps> = ({
  value,
  max,
  min = 0,
  label,
  unit = '',
  size = 'md',
  segments = [
    { threshold: 0.6, color: '#1B998B' },
    { threshold: 0.85, color: '#F46036' },
    { threshold: 1, color: '#EF4444' },
  ],
  showValue = true,
}) => {
  const sizeMap = {
    sm: { width: 100, height: 50, strokeWidth: 8 },
    md: { width: 140, height: 70, strokeWidth: 10 },
    lg: { width: 200, height: 100, strokeWidth: 12 },
  };

  const { width, height, strokeWidth } = sizeMap[size];
  const radius = (width - strokeWidth) / 2;
  const centerX = width / 2;
  const centerY = height;
  const normalizedValue = Math.min(1, Math.max(0, (value - min) / (max - min)));
  const angle = Math.PI * normalizedValue;

  const endX = centerX + radius * Math.cos(Math.PI + angle);
  const endY = centerY + radius * Math.sin(Math.PI + angle);

  const largeArc = normalizedValue > 0.5 ? 1 : 0;

  const getColor = () => {
    for (const seg of segments) {
      if (normalizedValue <= seg.threshold) return seg.color;
    }
    return segments[segments.length - 1].color;
  };

  const color = getColor();

  return (
    <div className="flex flex-col items-center">
      <svg width={width} height={height} className="overflow-visible">
        <defs>
          <linearGradient id={`gauge-gradient-${label}`} x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#3369B8" stopOpacity="0.3" />
            <stop offset="100%" stopColor={color} stopOpacity="0.6" />
          </linearGradient>
          <filter id={`glow-${label}`}>
            <feGaussianBlur stdDeviation="2" result="coloredBlur" />
            <feMerge>
              <feMergeNode in="coloredBlur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>

        <path
          d={`M ${centerX - radius} ${centerY} A ${radius} ${radius} 0 1 1 ${centerX + radius} ${centerY}`}
          fill="none"
          stroke="#323F4B"
          strokeWidth={strokeWidth}
          strokeLinecap="round"
        />

        <motion.path
          initial={{ pathLength: 0 }}
          animate={{ pathLength: normalizedValue }}
          transition={{ duration: 1, ease: 'easeOut' }}
          d={`M ${centerX - radius} ${centerY} A ${radius} ${radius} 0 ${largeArc} 1 ${endX} ${endY}`}
          fill="none"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          filter={`url(#glow-${label})`}
        />

        {showValue && (
          <motion.text
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5 }}
            x={centerX}
            y={centerY - 10}
            textAnchor="middle"
            fill={color}
            className="font-mono font-bold"
            style={{ fontSize: size === 'sm' ? 14 : size === 'md' ? 18 : 24 }}
          >
            {value.toFixed(1)}
            <tspan fill="#9AA5B1" fontSize={size === 'sm' ? 8 : 10}>
              {unit}
            </tspan>
          </motion.text>
        )}
      </svg>

      <span className="data-label text-center mt-1">{label}</span>
    </div>
  );
};

// BoilerPulses/src/components/GaugeMeter.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import * as d3 from 'd3';

  export let value;
  export let max = 100;
  export let min = 0;
  export let label = '效率';
  export let unit = '%';
  export let thresholds = { warning: 85, danger: 75 };

  let container;
  let svg;
  let width = 240;
  let height = 140;

  $: percentage = ((value - min) / (max - min)) * 100;
  $: color = value >= thresholds.warning ? '#10b981' : value >= thresholds.danger ? '#f59e0b' : '#ef4444';

  function render() {
    if (!container) return;
    d3.select(container).selectAll('*').remove();
    svg = d3.select(container)
      .append('svg')
      .attr('width', width)
      .attr('height', height)
      .attr('viewBox', `0 0 ${width} ${height}`);
    const centerX = width / 2;
    const centerY = height * 0.75;
    const radius = Math.min(width, height * 1.5) / 2 - 20;
    const startAngle = Math.PI * 0.75;
    const endAngle = Math.PI * 2.25;
    const arcAngle = startAngle + (percentage / 100) * (endAngle - startAngle);
    const bgArc = d3.arc()
      .innerRadius(radius - 15)
      .outerRadius(radius)
      .startAngle(startAngle)
      .endAngle(endAngle);
    svg.append('path')
      .attr('d', bgArc)
      .attr('fill', '#1e293b')
      .attr('transform', `translate(${centerX}, ${centerY})`);
    const valueArc = d3.arc()
      .innerRadius(radius - 15)
      .outerRadius(radius)
      .startAngle(startAngle)
      .endAngle(arcAngle);
    const gradient = svg.append('defs')
      .append('linearGradient')
      .attr('id', 'gauge-gradient')
      .attr('x1', '0%')
      .attr('y1', '0%')
      .attr('x2', '100%')
      .attr('y2', '0%');
    gradient.append('stop').attr('offset', '0%').attr('stop-color', color).attr('stop-opacity', 0.8);
    gradient.append('stop').attr('offset', '100%').attr('stop-color', color);
    svg.append('path')
      .attr('d', valueArc)
      .attr('fill', 'url(#gauge-gradient)')
      .attr('transform', `translate(${centerX}, ${centerY})`)
      .attr('filter', 'drop-shadow(0 0 8px ' + color + ')');
    const tickCount = 11;
    for (let i = 0; i < tickCount; i++) {
      const tickAngle = startAngle + (i / (tickCount - 1)) * (endAngle - startAngle);
      const innerR = radius - 22;
      const outerR = i % 2 === 0 ? radius - 18 : radius - 20;
      const x1 = centerX + innerR * Math.cos(tickAngle);
      const y1 = centerY + innerR * Math.sin(tickAngle);
      const x2 = centerX + outerR * Math.cos(tickAngle);
      const y2 = centerY + outerR * Math.sin(tickAngle);
      svg.append('line')
        .attr('x1', x1)
        .attr('y1', y1)
        .attr('x2', x2)
        .attr('y2', y2)
        .attr('stroke', '#475569')
        .attr('stroke-width', i % 2 === 0 ? 2 : 1);
    }
    svg.append('text')
      .attr('x', centerX)
      .attr('y', centerY - 10)
      .attr('text-anchor', 'middle')
      .attr('fill', color)
      .style('font-size', '32px')
      .style('font-weight', 'bold')
      .style('font-variant-numeric', 'tabular-nums')
      .text(value.toFixed(1));
    svg.append('text')
      .attr('x', centerX)
      .attr('y', centerY + 15)
      .attr('text-anchor', 'middle')
      .attr('fill', '#64748b')
      .style('font-size', '14px')
      .text(`${label} (${unit})`);
    [
      { value: min, label: min },
      { value: (min + max) / 2, label: (min + max) / 2 },
      { value: max, label: max }
    ].forEach((tick, i) => {
      const angle = startAngle + (i / 2) * (endAngle - startAngle);
      const r = radius + 10;
      const x = centerX + r * Math.cos(angle);
      const y = centerY + r * Math.sin(angle);
      svg.append('text')
        .attr('x', x)
        .attr('y', y)
        .attr('text-anchor', 'middle')
        .attr('fill', '#64748b')
        .style('font-size', '10px')
        .text(tick.label);
    });
  }

  $: if (svg) render();

  onMount(() => {
    render();
  });
</script>

<div bind:this={container} class="gauge-container"></div>

<style>
  .gauge-container {
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>
