// StackMatrixs/src/components/common/ProgressBar.tsx
import React from 'react';
import { classNames } from '@/utils/formatters';

interface ProgressBarProps {
  value: number;
  max?: number;
  label?: string;
  showPercentage?: boolean;
  color?: 'primary' | 'success' | 'warning' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

export const ProgressBar: React.FC<ProgressBarProps> = ({
  value,
  max = 100,
  label,
  showPercentage = false,
  color = 'primary',
  size = 'md',
  className = '',
}) => {
  const percentage = Math.min(100, Math.max(0, (value / max) * 100));

  const colorClasses = {
    primary: 'bg-wms-primary',
    success: 'bg-wms-success',
    warning: 'bg-wms-warning',
    danger: 'bg-wms-danger',
  };

  const sizeClasses = {
    sm: 'h-1.5',
    md: 'h-2.5',
    lg: 'h-4',
  };

  return (
    <div className={classNames('w-full', className)}>
      {(label || showPercentage) && (
        <div className="flex items-center justify-between mb-1">
          {label && <span className="text-xs text-wms-subtext">{label}</span>}
          {showPercentage && (
            <span className="text-xs font-medium text-wms-text">{percentage.toFixed(1)}%</span>
          )}
        </div>
      )}
      <div
        className={classNames(
          'w-full bg-wms-bg rounded-full overflow-hidden',
          sizeClasses[size]
        )}
      >
        <div
          className={classNames(
            'h-full rounded-full transition-all duration-500 ease-out',
            colorClasses[color]
          )}
          style={{ width: `${percentage}%` }}
        />
      </div>
    </div>
  );
};

// GridPulse/src/lib/components/ui/ProgressBar.svelte
<script lang="ts">
  export let value: number = 0;
  export let max: number = 100;
  export let label: string = '';
  export let showValue: boolean = true;
  export let color: 'accent' | 'green' | 'yellow' | 'red' = 'accent';

  $: percentage = Math.min(100, Math.max(0, (value / max) * 100));
  $: colorClass = color === 'accent' ? 'bg-accent-500' : 
                  color === 'green' ? 'bg-green-500' : 
                  color === 'yellow' ? 'bg-yellow-500' : 'bg-red-500';
</script>

<div class="w-full">
  {#if label}
    <div class="flex justify-between items-center mb-1">
      <span class="text-sm text-dark-400">{label}</span>
      {#if showValue}
        <span class="text-sm font-mono text-white">{value.toFixed(1)}%</span>
      {/if}
    </div>
  {/if}
  <div class="w-full h-2 bg-dark-700 rounded-full overflow-hidden">
    <div 
      class={`h-full ${colorClass} transition-all duration-300 ease-out rounded-full`}
      style={`width: ${percentage}%`}
    ></div>
  </div>
</div>
