// KnowledgeLink/src/lib/components/layout/Sidebar.svelte
<script lang="ts">
import { BookOpen, FileText, Brain, Share2, BarChart3, Link, WifiOff } from 'lucide-svelte'

let { currentRoute = '' }: { currentRoute: string } = $props()

const navItems = [
  { route: '/library', label: 'Library', icon: BookOpen },
  { route: '/notes', label: 'Notes', icon: FileText },
  { route: '/review', label: 'Review', icon: Brain },
  { route: '/graph', label: 'Graph', icon: Share2 },
  { route: '/dashboard', label: 'Dashboard', icon: BarChart3 },
]

function isActive(route: string): boolean {
  if (route === '/library') {
    return currentRoute === '/library' || currentRoute.startsWith('/library/') || currentRoute === '/'
  }
  return currentRoute === route || currentRoute.startsWith(route + '/')
}

function navigate(route: string) {
  window.location.hash = route
}
</script>

<aside class="w-[240px] h-screen bg-bg flex flex-col border-r border-border shrink-0">
  <div class="px-5 py-6 flex items-center gap-2.5">
    <Link size={22} class="text-accent" />
    <span class="font-display text-xl font-bold text-accent tracking-wide">KnowledgeLink</span>
  </div>

  <nav class="flex-1 px-2 mt-2 flex flex-col gap-0.5">
    {#each navItems as item}
      {@const active = isActive(item.route)}
      <button
        class="flex items-center gap-3 px-3 py-2.5 rounded-md text-sm transition-colors duration-150 w-full text-left
          {active
            ? 'bg-surface text-accent border-l-[3px] border-accent'
            : 'text-text-secondary hover:bg-surface hover:text-text border-l-[3px] border-transparent'}"
        onclick={() => navigate(item.route)}
      >
        <item.icon size={18} />
        <span>{item.label}</span>
      </button>
    {/each}
  </nav>

  <div class="px-5 py-4 border-t border-border flex items-center gap-2 text-text-secondary text-xs">
    <WifiOff size={12} />
    <span>v1.0 · 离线模式</span>
  </div>
</aside>

// ValveLogic/src/components/layout/Sidebar.tsx
import React from 'react';
import { LayoutDashboard, Network, ToggleLeft, BarChart3, Settings } from 'lucide-react';

type Route = 'dashboard' | 'network' | 'valves' | 'analysis' | 'settings';

const navItems: { id: Route; label: string; icon: React.ElementType }[] = [
  { id: 'dashboard', label: '监控面板', icon: LayoutDashboard },
  { id: 'network', label: '管网建模', icon: Network },
  { id: 'valves', label: '阀门控制', icon: ToggleLeft },
  { id: 'analysis', label: '数据分析', icon: BarChart3 },
  { id: 'settings', label: '系统设置', icon: Settings },
];

interface SidebarProps {
  currentRoute: Route;
  onNavigate: (route: Route) => void;
}

export const Sidebar: React.FC<SidebarProps> = ({ currentRoute, onNavigate }) => {
  return (
    <div className="w-64 bg-slate-900 border-r border-slate-800 flex flex-col h-full">
      <div className="p-6 border-b border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-400 rounded-lg flex items-center justify-center">
            <ToggleLeft className="text-white" size={20} />
          </div>
          <div>
            <h1 className="text-white font-bold text-lg">ValveLogic</h1>
            <p className="text-xs text-slate-400">水锤效应仿真系统</p>
          </div>
        </div>
      </div>

      <nav className="flex-1 p-4 space-y-1">
        {navItems.map((item) => (
          <button
            key={item.id}
            onClick={() => onNavigate(item.id)}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-all ${
              currentRoute === item.id
                ? 'bg-blue-600/20 text-blue-400 border border-blue-500/30'
                : 'text-slate-400 hover:bg-slate-800 hover:text-white'
            }`}
          >
            <item.icon size={18} />
            <span className="font-medium">{item.label}</span>
          </button>
        ))}
      </nav>

      <div className="p-4 border-t border-slate-800">
        <div className="bg-slate-800/50 rounded-lg p-3">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
            <span className="text-xs text-green-400">系统运行正常</span>
          </div>
          <p className="text-xs text-slate-500">版本 1.0.0</p>
        </div>
      </div>
    </div>
  );
};
