// BeltNexus/src/components/dashboard/StatCard.tsx
import { Component } from 'solid-js';
import { formatNumber } from '@/utils/format';

interface StatCardProps {
  title: string;
  value: number;
  unit: string;
  icon: string;
  color?: 'blue' | 'green' | 'yellow' | 'red';
  trend?: number;
  decimals?: number;
}

export const StatCard: Component<StatCardProps> = (props) => {
  const colorClasses = {
    blue: 'from-industrial-500/20 to-industrial-600/20 border-industrial-500/30',
    green: 'from-green-500/20 to-green-600/20 border-green-500/30',
    yellow: 'from-yellow-500/20 to-yellow-600/20 border-yellow-500/30',
    red: 'from-red-500/20 to-red-600/20 border-red-500/30',
  };

  const iconColors = {
    blue: 'text-industrial-400',
    green: 'text-green-400',
    yellow: 'text-yellow-400',
    red: 'text-red-400',
  };

  return (
    <div
      class={`relative overflow-hidden rounded-xl border bg-gradient-to-br p-4 backdrop-blur-sm transition-all duration-300 hover:scale-[1.02] hover:shadow-lg ${
        colorClasses[props.color || 'blue']
      }`}
    >
      <div class="absolute top-0 right-0 h-20 w-20 opacity-10">
        <svg viewBox="0 0 24 24" fill="currentColor" class={iconColors[props.color || 'blue']}>
          <path d={props.icon} />
        </svg>
      </div>
      
      <div class="relative z-10">
        <div class="text-sm text-gray-400 mb-1">{props.title}</div>
        <div class="flex items-baseline gap-2">
          <span class="text-2xl font-bold font-mono text-white">
            {formatNumber(props.value, props.decimals ?? 1)}
          </span>
          <span class="text-sm text-gray-400">{props.unit}</span>
        </div>
        {props.trend !== undefined && (
          <div class={`mt-1 text-xs ${props.trend >= 0 ? 'text-green-400' : 'text-red-400'}`}>
            {props.trend >= 0 ? '↑' : '↓'} {Math.abs(props.trend).toFixed(1)}%
          </div>
        )}
      </div>
    </div>
  );
};

// SolarNexust/src/components/dashboard/StatCard.tsx
import { motion } from 'framer-motion';
import type { LucideIcon } from 'lucide-react';

interface StatCardProps {
  title: string;
  value: string;
  subtitle?: string;
  icon: LucideIcon;
  trend?: {
    value: number;
    isPositive: boolean;
  };
  color?: 'cyan' | 'emerald' | 'yellow' | 'orange' | 'red' | 'blue';
}

const colorMap = {
  cyan: {
    bg: 'from-cyan-500/20 to-cyan-500/5',
    border: 'border-cyan-500/30',
    icon: 'text-cyan-400',
    value: 'text-cyan-300',
  },
  emerald: {
    bg: 'from-emerald-500/20 to-emerald-500/5',
    border: 'border-emerald-500/30',
    icon: 'text-emerald-400',
    value: 'text-emerald-300',
  },
  yellow: {
    bg: 'from-yellow-500/20 to-yellow-500/5',
    border: 'border-yellow-500/30',
    icon: 'text-yellow-400',
    value: 'text-yellow-300',
  },
  orange: {
    bg: 'from-orange-500/20 to-orange-500/5',
    border: 'border-orange-500/30',
    icon: 'text-orange-400',
    value: 'text-orange-300',
  },
  red: {
    bg: 'from-red-500/20 to-red-500/5',
    border: 'border-red-500/30',
    icon: 'text-red-400',
    value: 'text-red-300',
  },
  blue: {
    bg: 'from-blue-500/20 to-blue-500/5',
    border: 'border-blue-500/30',
    icon: 'text-blue-400',
    value: 'text-blue-300',
  },
};

export function StatCard({
  title,
  value,
  subtitle,
  icon: Icon,
  trend,
  color = 'cyan',
}: StatCardProps) {
  const colors = colorMap[color];
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`relative overflow-hidden rounded-2xl border ${colors.border} bg-gradient-to-br ${colors.bg} backdrop-blur-md p-6`}
    >
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm font-medium text-slate-400">{title}</p>
          <motion.p
            key={value}
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className={`mt-2 text-3xl font-bold font-mono ${colors.value}`}
          >
            {value}
          </motion.p>
          {subtitle && (
            <p className="mt-1 text-xs text-slate-500">{subtitle}</p>
          )}
          {trend && (
            <div className={`mt-2 flex items-center gap-1 text-xs ${trend.isPositive ? 'text-emerald-400' : 'text-red-400'}`}>
              <span>{trend.isPositive ? '↑' : '↓'}</span>
              <span>{trend.value.toFixed(1)}%</span>
              <span className="text-slate-500">较昨日</span>
            </div>
          )}
        </div>
        <div className={`p-3 rounded-xl bg-slate-900/50 ${colors.icon}`}>
          <Icon size={24} />
        </div>
      </div>
    </motion.div>
  );
}
