// UAVScan/src/components/common/StatCard.vue
<template>
  <div class="cyber-card-hover group">
    <div class="flex items-start justify-between">
      <div>
        <p class="text-sm text-cyber-text-secondary mb-1">{{ title }}</p>
        <p class="text-2xl font-bold font-mono text-cyber-text group-hover:text-electric-blue transition-colors">
          {{ formattedValue }}
        </p>
        <p v-if="subtitle" class="text-xs text-cyber-text-muted mt-1">{{ subtitle }}</p>
      </div>
      <div
        class="w-12 h-12 rounded-xl flex items-center justify-center transition-all duration-300 group-hover:scale-110"
        :class="iconBgClass"
      >
        <component :is="iconComponent" class="w-6 h-6" :class="iconClass" />
      </div>
    </div>
    
    <div v-if="trend !== undefined" class="mt-3 flex items-center gap-1">
      <component
        :is="trend >= 0 ? icons.TrendingUp : icons.TrendingDown"
        class="w-4 h-4"
        :class="trend >= 0 ? 'text-success-green' : 'text-error-red'"
      />
      <span
        class="text-xs font-medium"
        :class="trend >= 0 ? 'text-success-green' : 'text-error-red'"
      >
        {{ trend >= 0 ? '+' : '' }}{{ trend }}%
      </span>
      <span class="text-xs text-cyber-text-muted">较昨日</span>
    </div>

    <div v-if="progress !== undefined" class="mt-3">
      <div class="flex justify-between text-xs mb-1">
        <span class="text-cyber-text-secondary">{{ progressLabel }}</span>
        <span class="text-cyber-text font-mono">{{ progress }}%</span>
      </div>
      <div class="cyber-progress-bar">
        <div
          class="cyber-progress-fill"
          :style="{ width: `${progress}%` }"
        ></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, type Component } from 'vue'
import { TrendingUp, TrendingDown } from 'lucide-vue-next'

const icons = {
  TrendingUp,
  TrendingDown
}

const props = defineProps<{
  title: string
  value: number | string
  subtitle?: string
  icon: Component
  iconVariant?: 'blue' | 'green' | 'orange' | 'red' | 'purple'
  trend?: number
  progress?: number
  progressLabel?: string
  format?: 'number' | 'bytes' | 'percent' | 'time'
}>()

const iconComponent = computed(() => props.icon)

const iconBgClass = computed(() => {
  const variants: Record<string, string> = {
    blue: 'bg-electric-blue/10',
    green: 'bg-success-green/10',
    orange: 'bg-warning-orange/10',
    red: 'bg-error-red/10',
    purple: 'bg-electric-purple/10'
  }
  return variants[props.iconVariant || 'blue']
})

const iconClass = computed(() => {
  const variants: Record<string, string> = {
    blue: 'text-electric-blue',
    green: 'text-success-green',
    orange: 'text-warning-orange',
    red: 'text-error-red',
    purple: 'text-electric-purple'
  }
  return variants[props.iconVariant || 'blue']
})

const formattedValue = computed(() => {
  if (typeof props.value === 'string') return props.value
  
  switch (props.format) {
    case 'bytes':
      return formatBytes(props.value)
    case 'percent':
      return `${props.value.toFixed(1)}%`
    case 'time':
      return formatTime(props.value)
    case 'number':
    default:
      return formatNumber(props.value)
  }
})

function formatNumber(num: number): string {
  if (num >= 1e9) return (num / 1e9).toFixed(2) + 'B'
  if (num >= 1e6) return (num / 1e6).toFixed(2) + 'M'
  if (num >= 1e3) return (num / 1e3).toFixed(2) + 'K'
  return num.toString()
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

function formatTime(ms: number): string {
  if (ms < 1000) return `${ms}ms`
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`
  return `${(ms / 60000).toFixed(1)}min`
}
</script>

// SolarNexust/src/components/dashboard/StatCard.tsx
import { motion } from 'framer-motion';
import type { LucideIcon } from 'lucide-react';

interface StatCardProps {
  title: string;
  value: string;
  subtitle?: string;
  icon: LucideIcon;
  trend?: {
    value: number;
    isPositive: boolean;
  };
  color?: 'cyan' | 'emerald' | 'yellow' | 'orange' | 'red' | 'blue';
}

const colorMap = {
  cyan: {
    bg: 'from-cyan-500/20 to-cyan-500/5',
    border: 'border-cyan-500/30',
    icon: 'text-cyan-400',
    value: 'text-cyan-300',
  },
  emerald: {
    bg: 'from-emerald-500/20 to-emerald-500/5',
    border: 'border-emerald-500/30',
    icon: 'text-emerald-400',
    value: 'text-emerald-300',
  },
  yellow: {
    bg: 'from-yellow-500/20 to-yellow-500/5',
    border: 'border-yellow-500/30',
    icon: 'text-yellow-400',
    value: 'text-yellow-300',
  },
  orange: {
    bg: 'from-orange-500/20 to-orange-500/5',
    border: 'border-orange-500/30',
    icon: 'text-orange-400',
    value: 'text-orange-300',
  },
  red: {
    bg: 'from-red-500/20 to-red-500/5',
    border: 'border-red-500/30',
    icon: 'text-red-400',
    value: 'text-red-300',
  },
  blue: {
    bg: 'from-blue-500/20 to-blue-500/5',
    border: 'border-blue-500/30',
    icon: 'text-blue-400',
    value: 'text-blue-300',
  },
};

export function StatCard({
  title,
  value,
  subtitle,
  icon: Icon,
  trend,
  color = 'cyan',
}: StatCardProps) {
  const colors = colorMap[color];
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`relative overflow-hidden rounded-2xl border ${colors.border} bg-gradient-to-br ${colors.bg} backdrop-blur-md p-6`}
    >
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm font-medium text-slate-400">{title}</p>
          <motion.p
            key={value}
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className={`mt-2 text-3xl font-bold font-mono ${colors.value}`}
          >
            {value}
          </motion.p>
          {subtitle && (
            <p className="mt-1 text-xs text-slate-500">{subtitle}</p>
          )}
          {trend && (
            <div className={`mt-2 flex items-center gap-1 text-xs ${trend.isPositive ? 'text-emerald-400' : 'text-red-400'}`}>
              <span>{trend.isPositive ? '↑' : '↓'}</span>
              <span>{trend.value.toFixed(1)}%</span>
              <span className="text-slate-500">较昨日</span>
            </div>
          )}
        </div>
        <div className={`p-3 rounded-xl bg-slate-900/50 ${colors.icon}`}>
          <Icon size={24} />
        </div>
      </div>
    </motion.div>
  );
}
