// PoseNexus/src/components/pose/ScoreRing.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  score: number
  size?: number
  thickness?: number
}>()

const size = computed(() => props.size || 120)
const thickness = computed(() => props.thickness || 8)
const radius = computed(() => (size.value - thickness.value) / 2)
const circumference = computed(() => 2 * Math.PI * radius.value)
const strokeDashoffset = computed(() => {
  const progress = Math.min(100, Math.max(0, props.score)) / 100
  return circumference.value * (1 - progress)
})

const getColor = computed(() => {
  if (props.score >= 90) return '#FBBF24'
  if (props.score >= 80) return '#00B42A'
  if (props.score >= 70) return '#165DFF'
  if (props.score >= 60) return '#FF7D00'
  return '#F53F3F'
})

const getGrade = computed(() => {
  if (props.score >= 90) return 'S'
  if (props.score >= 80) return 'A'
  if (props.score >= 70) return 'B'
  if (props.score >= 60) return 'C'
  return 'D'
})
</script>

<template>
  <div class="relative" :style="{ width: size + 'px', height: size + 'px' }">
    <svg :width="size" :height="size" class="transform -rotate-90">
      <circle
        :cx="size / 2"
        :cy="size / 2"
        :r="radius"
        fill="none"
        :stroke="getColor"
        stroke-opacity="0.2"
        :stroke-width="thickness"
      />
      <circle
        :cx="size / 2"
        :cy="size / 2"
        :r="radius"
        fill="none"
        :stroke="getColor"
        :stroke-width="thickness"
        stroke-linecap="round"
        :stroke-dasharray="circumference"
        :stroke-dashoffset="strokeDashoffset"
        class="transition-all duration-300 ease-out"
        :style="{ filter: `drop-shadow(0 0 8px ${getColor})` }"
      />
    </svg>
    <div class="absolute inset-0 flex flex-col items-center justify-center">
      <span
        class="text-3xl font-bold"
        :style="{ color: getColor }"
      >
        {{ Math.round(score) }}
      </span>
      <span
        class="text-xs font-medium"
        :style="{ color: getColor }"
      >
        {{ getGrade }}
      </span>
    </div>
  </div>
</template>

// DermaLogic/src/components/ScoreRing.svelte
<script lang="ts">
  export let score: number
  export let size = 120
  export let strokeWidth = 8

  const radius = (size - strokeWidth) / 2
  const circumference = radius * 2 * Math.PI
  const offset = circumference - (score / 100) * circumference

  $: color = score >= 80 ? '#10B981' : score >= 60 ? '#F59E0B' : '#EF4444'
</script>

<div class="relative inline-flex items-center justify-center" style="width: {size}px; height: {size}px;">
  <svg class="transform -rotate-90" width={size} height={size}>
    <circle
      cx={size / 2}
      cy={size / 2}
      r={radius}
      fill="none"
      stroke="#E5E7EB"
      stroke-width={strokeWidth}
    />
    <circle
      cx={size / 2}
      cy={size / 2}
      r={radius}
      fill="none"
      stroke={color}
      stroke-width={strokeWidth}
      stroke-dasharray={circumference}
      stroke-dashoffset={offset}
      stroke-linecap="round"
      class="transition-all duration-1000 ease-out"
    />
  </svg>
  <div class="absolute inset-0 flex flex-col items-center justify-center">
    <span class="text-3xl font-bold text-gray-800">{score}</span>
    <span class="text-xs text-gray-500">肤质评分</span>
  </div>
</div>
