// MoldNexus/src/components/layout/Sidebar.tsx
import { Component } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import {
  LayoutDashboard,
  Beaker,
  Database,
  ArrowRightLeft,
  Users,
  BarChart3,
  Settings,
  ChevronLeft,
  ChevronRight,
} from 'lucide-solid';
import { useAppStore } from '@/stores/appStore';

const menuItems = [
  { path: '/', icon: LayoutDashboard, label: '仪表盘' },
  { path: '/simulation', icon: Beaker, label: '模拟工作台' },
  { path: '/parameters', icon: Database, label: '参数管理' },
  { path: '/mapping', icon: ArrowRightLeft, label: '语义映射' },
  { path: '/collaboration', icon: Users, label: '协作中心' },
  { path: '/analytics', icon: BarChart3, label: '分析报告' },
  { path: '/settings', icon: Settings, label: '系统设置' },
];

const Sidebar: Component = () => {
  const location = useLocation();
  const { state, toggleSidebar } = useAppStore();

  return (
    <aside
      class={`fixed left-0 top-14 bottom-0 bg-dark-200 border-r border-dark-100 transition-all duration-300 z-40 ${
        state.sidebarCollapsed ? 'w-16' : 'w-64'
      }`}
    >
      <div class="flex flex-col h-full">
        <nav class="flex-1 py-4">
          <ul class="space-y-1 px-2">
            {menuItems.map((item) => {
              const isActive = location.pathname === item.path;
              return (
                <li>
                  <A
                    href={item.path}
                    class={`flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 ${
                      isActive
                        ? 'bg-primary-600 text-white shadow-lg shadow-primary-600/30'
                        : 'text-gray-400 hover:bg-dark-100 hover:text-gray-200'
                    }`}
                  >
                    <item.icon class="w-5 h-5 flex-shrink-0" />
                    {!state.sidebarCollapsed && (
                      <span class="text-sm font-medium">{item.label}</span>
                    )}
                  </A>
                </li>
              );
            })}
          </ul>
        </nav>

        <button
          onClick={toggleSidebar}
          class="p-3 border-t border-dark-100 text-gray-400 hover:text-gray-200 hover:bg-dark-100 transition-colors flex items-center justify-center"
        >
          {state.sidebarCollapsed ? (
            <ChevronRight class="w-5 h-5" />
          ) : (
            <ChevronLeft class="w-5 h-5" />
          )}
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;

// SolarNexust/src/components/layout/Sidebar.tsx
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
import { Sun, BarChart3, Wrench, Database, Settings, ChevronLeft, ChevronRight } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const menuItems = [
  { icon: Sun, label: '仿真工作台', path: '/simulation' },
  { icon: BarChart3, label: '能效监控', path: '/monitoring' },
  { icon: Wrench, label: '运维管理', path: '/operation' },
  { icon: Database, label: '数据管理', path: '/data-manage' },
  { icon: Settings, label: '系统设置', path: '/settings' },
];

export default function Sidebar() {
  const [collapsed, setCollapsed] = useState(false);
  
  return (
    <motion.aside
      initial={{ width: 240 }}
      animate={{ width: collapsed ? 72 : 240 }}
      className="h-full bg-slate-900/80 backdrop-blur-xl border-r border-slate-700/50 flex flex-col"
    >
      <div className="p-4 border-b border-slate-700/50">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-400 to-emerald-500 flex items-center justify-center flex-shrink-0">
            <Sun className="text-white" size={22} />
          </div>
          <AnimatePresence mode="wait">
            {!collapsed && (
              <motion.div
                initial={{ opacity: 0, width: 0 }}
                animate={{ opacity: 1, width: 'auto' }}
                exit={{ opacity: 0, width: 0 }}
                className="overflow-hidden"
              >
                <h1 className="text-lg font-bold text-white whitespace-nowrap">SolarNexus</h1>
                <p className="text-xs text-slate-400 whitespace-nowrap">光伏阵列仿真平台</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
      
      <nav className="flex-1 p-3 space-y-1">
        {menuItems.map((item) => (
          <NavLink
            key={item.path}
            to={item.path}
            className={({ isActive }) => `
              flex items-center gap-3 px-3 py-3 rounded-xl transition-all
              ${isActive
                ? 'bg-cyan-500/20 text-cyan-400 shadow-lg shadow-cyan-500/10'
                : 'text-slate-400 hover:bg-slate-800/50 hover:text-white'
              }
            `}
          >
            <item.icon size={20} className="flex-shrink-0" />
            <AnimatePresence mode="wait">
              {!collapsed && (
                <motion.span
                  initial={{ opacity: 0, width: 0 }}
                  animate={{ opacity: 1, width: 'auto' }}
                  exit={{ opacity: 0, width: 0 }}
                  className="text-sm font-medium whitespace-nowrap overflow-hidden"
                >
                  {item.label}
                </motion.span>
              )}
            </AnimatePresence>
          </NavLink>
        ))}
      </nav>
      
      <div className="p-3 border-t border-slate-700/50">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-xl text-slate-400 hover:bg-slate-800/50 hover:text-white transition-all"
        >
          {collapsed ? <ChevronRight size={18} /> : <ChevronLeft size={18} />}
          {!collapsed && <span className="text-sm">收起菜单</span>}
        </button>
      </div>
    </motion.aside>
  );
}
