// FabLogic/src/components/StatsCard.svelte
<script>
  let { title, value, icon = '', trend = null, color = 'primary' } = $props()

  const colorClasses = {
    primary: 'from-cyan-500/20 to-cyan-500/5 border-cyan-500/30',
    success: 'from-emerald-500/20 to-emerald-500/5 border-emerald-500/30',
    warning: 'from-amber-500/20 to-amber-500/5 border-amber-500/30',
    danger: 'from-red-500/20 to-red-500/5 border-red-500/30',
    purple: 'from-purple-500/20 to-purple-500/5 border-purple-500/30'
  }

  const textColors = {
    primary: 'text-cyan-400',
    success: 'text-emerald-400',
    warning: 'text-amber-400',
    danger: 'text-red-400',
    purple: 'text-purple-400'
  }
</script>

<div class="stats-card bg-gradient-to-br {colorClasses[color]} border rounded-xl p-5 backdrop-blur-sm">
  <div class="flex items-start justify-between">
    <div>
      <p class="text-sm text-slate-400 mb-1">{title}</p>
      <p class="text-3xl font-bold text-white">{value}</p>
      {#if trend !== null}
        <p class="text-xs mt-1 {trend >= 0 ? 'text-emerald-400' : 'text-red-400'}">
          {trend >= 0 ? '↑' : '↓'} {Math.abs(trend)}%
        </p>
      {/if}
    </div>
    {#if icon}
      <div class="text-3xl {textColors[color]}">{icon}</div>
    {/if}
  </div>
</div>

// CyberNexus/src/presentation/components/ui/StatsCard.tsx
import type { Component, JSX } from 'solid-js';

interface StatsCardProps {
  icon: string;
  label: string;
  value: number | string;
  trend?: {
    value: number;
    label: string;
  };
  color?: 'blue' | 'green' | 'yellow' | 'red' | 'purple';
  children?: JSX.Element;
}

const colorClasses: Record<string, string> = {
  blue: 'bg-blue-900 text-blue-300',
  green: 'bg-green-900 text-green-300',
  yellow: 'bg-yellow-900 text-yellow-300',
  red: 'bg-red-900 text-red-300',
  purple: 'bg-purple-900 text-purple-300',
};

export const StatsCard: Component<StatsCardProps> = (props) => {
  const color = props.color || 'blue';

  return (
    <div class="bg-gray-800 rounded-lg p-6 border border-gray-700">
      <div class="flex items-start justify-between">
        <div>
          <p class="text-gray-400 text-sm">{props.label}</p>
          <p class="text-2xl font-bold text-white mt-1">{props.value}</p>
          {props.trend && (
            <p class={`text-xs mt-2 ${props.trend.value >= 0 ? 'text-green-400' : 'text-red-400'}`}>
              {props.trend.value >= 0 ? '↑' : '↓'} {Math.abs(props.trend.value)}% {props.trend.label}
            </p>
          )}
        </div>
        <div class={`w-12 h-12 ${colorClasses[color]} rounded-full flex items-center justify-center`}>
          <span class="text-2xl">{props.icon}</span>
        </div>
      </div>
      {props.children && <div class="mt-4">{props.children}</div>}
    </div>
  );
};
