// MoldNexus/src/components/layout/Sidebar.tsx
import { Component } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import {
  LayoutDashboard,
  Beaker,
  Database,
  ArrowRightLeft,
  Users,
  BarChart3,
  Settings,
  ChevronLeft,
  ChevronRight,
} from 'lucide-solid';
import { useAppStore } from '@/stores/appStore';

const menuItems = [
  { path: '/', icon: LayoutDashboard, label: '仪表盘' },
  { path: '/simulation', icon: Beaker, label: '模拟工作台' },
  { path: '/parameters', icon: Database, label: '参数管理' },
  { path: '/mapping', icon: ArrowRightLeft, label: '语义映射' },
  { path: '/collaboration', icon: Users, label: '协作中心' },
  { path: '/analytics', icon: BarChart3, label: '分析报告' },
  { path: '/settings', icon: Settings, label: '系统设置' },
];

const Sidebar: Component = () => {
  const location = useLocation();
  const { state, toggleSidebar } = useAppStore();

  return (
    <aside
      class={`fixed left-0 top-14 bottom-0 bg-dark-200 border-r border-dark-100 transition-all duration-300 z-40 ${
        state.sidebarCollapsed ? 'w-16' : 'w-64'
      }`}
    >
      <div class="flex flex-col h-full">
        <nav class="flex-1 py-4">
          <ul class="space-y-1 px-2">
            {menuItems.map((item) => {
              const isActive = location.pathname === item.path;
              return (
                <li>
                  <A
                    href={item.path}
                    class={`flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 ${
                      isActive
                        ? 'bg-primary-600 text-white shadow-lg shadow-primary-600/30'
                        : 'text-gray-400 hover:bg-dark-100 hover:text-gray-200'
                    }`}
                  >
                    <item.icon class="w-5 h-5 flex-shrink-0" />
                    {!state.sidebarCollapsed && (
                      <span class="text-sm font-medium">{item.label}</span>
                    )}
                  </A>
                </li>
              );
            })}
          </ul>
        </nav>

        <button
          onClick={toggleSidebar}
          class="p-3 border-t border-dark-100 text-gray-400 hover:text-gray-200 hover:bg-dark-100 transition-colors flex items-center justify-center"
        >
          {state.sidebarCollapsed ? (
            <ChevronRight class="w-5 h-5" />
          ) : (
            <ChevronLeft class="w-5 h-5" />
          )}
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;

// GeothermLogic/src/components/layout/Sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { LayoutDashboard, ThermometerSun, TrendingDown, Database, RefreshCw, Settings } from 'lucide-react';

const navigation = [
  { name: '系统首页', href: '/', icon: LayoutDashboard },
  { name: '热平衡分析', href: '/thermal-balance', icon: ThermometerSun },
  { name: '热漂移预测', href: '/thermal-drift', icon: TrendingDown },
  { name: '换热孔管理', href: '/boreholes', icon: Database },
  { name: '数据同步', href: '/data-sync', icon: RefreshCw },
  { name: '系统设置', href: '/settings', icon: Settings },
];

export default function Sidebar() {
  const pathname = usePathname();

  return (
    <aside className="fixed left-0 top-0 h-screen w-64 bg-gray-900 border-r border-gray-800">
      <div className="p-6 border-b border-gray-800">
        <h1 className="text-xl font-bold text-white flex items-center gap-2">
          <ThermometerSun className="w-6 h-6 text-primary-500" />
          GeothermLogic
        </h1>
        <p className="text-xs text-gray-400 mt-1">地热能源管理系统</p>
      </div>

      <nav className="p-4 space-y-1">
        {navigation.map((item) => {
          const isActive = pathname === item.href;
          return (
            <Link
              key={item.name}
              href={item.href}
              className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-200 ${
                isActive
                  ? 'bg-primary-600 text-white shadow-lg shadow-primary-600/20'
                  : 'text-gray-400 hover:bg-gray-800 hover:text-white'
              }`}
            >
              <item.icon className="w-5 h-5" />
              <span className="text-sm font-medium">{item.name}</span>
            </Link>
          );
        })}
      </nav>

      <div className="absolute bottom-0 left-0 right-0 p-4 border-t border-gray-800">
        <div className="bg-gray-800 rounded-lg p-4">
          <p className="text-xs text-gray-400 mb-2">系统状态</p>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
            <span className="text-sm text-white">运行正常</span>
          </div>
        </div>
      </div>
    </aside>
  );
}
