// MixLogic/src/App.vue
<template>
  <div class="app-container">
    <header class="header">
      <div class="logo">
        <div class="logo-icon">⚗️</div>
        <div class="logo-text">
          <h1>MixLogic</h1>
          <p>化工搅拌釜混合演化仿真系统</p>
        </div>
      </div>
      <nav class="nav">
        <router-link 
          v-for="route in navRoutes" 
          :key="route.path"
          :to="route.path" 
          class="nav-link"
          active-class="active"
        >
          <span class="nav-icon">{{ route.icon }}</span>
          <span class="nav-label">{{ route.label }}</span>
        </router-link>
      </nav>
      <div class="header-stats">
        <div class="stat-item">
          <span class="stat-icon">💾</span>
          <div class="stat-info">
            <span class="stat-value">{{ cacheCount }}</span>
            <span class="stat-label">缓存快照</span>
          </div>
        </div>
        <div class="stat-item">
          <span class="stat-icon">🔄</span>
          <div class="stat-info">
            <span class="stat-value">{{ syncStatus }}</span>
            <span class="stat-label">协同状态</span>
          </div>
        </div>
      </div>
    </header>
    <main class="main-content">
      <router-view />
    </main>
    <footer class="footer">
      <p>MixLogic v1.0.0 | 异步滑移网格数值模拟 | IndexedDB 流体特征缓存</p>
    </footer>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useSimulationStore } from './stores/simulation'

const store = useSimulationStore()

const navRoutes = [
  { path: '/simulation', label: '仿真模拟', icon: '🔬' },
  { path: '/database', label: '数据库', icon: '🗄️' },
  { path: '/collaboration', label: '数据协同', icon: '🔗' },
  { path: '/analysis', label: '分析报告', icon: '📊' }
]

const cacheCount = computed(() => store.snapshotCount)
const syncStatus = computed(() => store.syncStatus ? '已同步' : '待同步')
</script>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 32px;
  background: rgba(10, 10, 26, 0.9);
  border-bottom: 1px solid var(--border);
  backdrop-filter: blur(10px);
  position: sticky;
  top: 0;
  z-index: 100;
}

.logo {
  display: flex;
  align-items: center;
  gap: 12px;
}

.logo-icon {
  font-size: 36px;
  animation: rotate 10s linear infinite;
}

@keyframes rotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.logo-text h1 {
  font-size: 24px;
  background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  margin: 0;
}

.logo-text p {
  font-size: 11px;
  color: var(--text-secondary);
  margin: 0;
  letter-spacing: 1px;
}

.nav {
  display: flex;
  gap: 8px;
}

.nav-link {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 18px;
  border-radius: 8px;
  color: var(--text-secondary);
  text-decoration: none;
  font-size: 13px;
  font-weight: 500;
  transition: all 0.3s ease;
  border: 1px solid transparent;
}

.nav-link:hover {
  background: rgba(0, 212, 255, 0.1);
  color: var(--text-primary);
}

.nav-link.active {
  background: rgba(0, 212, 255, 0.15);
  border-color: var(--border);
  color: var(--primary);
}

.nav-icon {
  font-size: 16px;
}

.header-stats {
  display: flex;
  gap: 24px;
}

.stat-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 14px;
  background: var(--bg-glass);
  border-radius: 8px;
  border: 1px solid var(--border);
}

.stat-icon {
  font-size: 18px;
}

.stat-info {
  display: flex;
  flex-direction: column;
}

.stat-value {
  font-size: 14px;
  font-weight: 600;
  color: var(--primary);
}

.stat-label {
  font-size: 10px;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.main-content {
  flex: 1;
  padding: 24px 32px;
}

.footer {
  padding: 16px 32px;
  text-align: center;
  border-top: 1px solid var(--border);
  background: rgba(10, 10, 26, 0.8);
}

.footer p {
  margin: 0;
  font-size: 12px;
  color: var(--text-secondary);
}
</style>

// RoadGuard/src/App.svelte
<script lang="ts">
  import Header from './components/Header.svelte';
  import Dashboard from './components/Dashboard.svelte';
  import SemanticMappingPanel from './components/SemanticMappingPanel.svelte';
  import TrendSimulationPanel from './components/TrendSimulationPanel.svelte';
  import SnapshotManager from './components/SnapshotManager.svelte';
  import { semanticMappingService } from './services/semanticMapping';
  import { interpolationService } from './services/interpolation';
  import { snapshotService } from './services/snapshot';
  import { dataStore } from './services/dataStore';

  let activeTab = $state<'dashboard' | 'mapping' | 'simulation' | 'snapshots'>('dashboard');
  let isInitialized = $state(false);
  let initError = $state<string | null>(null);

  async function initServices() {
    try {
      await dataStore.init();
      await semanticMappingService.init();
      await snapshotService.init();
      isInitialized = true;
    } catch (error) {
      initError = error instanceof Error ? error.message : '初始化失败';
    }
  }

  $effect(() => {
    initServices();
  });

  const tabs = [
    { id: 'dashboard' as const, label: '数据总览', icon: '📊' },
    { id: 'mapping' as const, label: '语义映射', icon: '🔄' },
    { id: 'simulation' as const, label: '趋势模拟', icon: '📈' },
    { id: 'snapshots' as const, label: '影像快照', icon: '📸' }
  ];
</script>

<div class="app-container">
  <Header />

  {#if initError}
    <div class="error-panel">
      <p>初始化错误: {initError}</p>
    </div>
  {:else if !isInitialized}
    <div class="loading-panel">
      <div class="spinner"></div>
      <p>正在初始化系统...</p>
    </div>
  {:else}
    <nav class="tab-nav">
      {#each tabs as tab}
        <button
          class={`tab-btn ${activeTab === tab.id ? 'active' : ''}`}
          onclick={() => (activeTab = tab.id)}
        >
          <span class="tab-icon">{tab.icon}</span>
          <span>{tab.label}</span>
        </button>
      {/each}
    </nav>

    <main class="main-content">
      {#if activeTab === 'dashboard'}
        <Dashboard />
      {:else if activeTab === 'mapping'}
        <SemanticMappingPanel />
      {:else if activeTab === 'simulation'}
        <TrendSimulationPanel {interpolationService} />
      {:else if activeTab === 'snapshots'}
        <SnapshotManager {snapshotService} />
      {/if}
    </main>
  {/if}
</div>

<style>
  .app-container {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
  }

  .loading-panel, .error-panel {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex: 1;
    padding: 40px;
  }

  .spinner {
    width: 40px;
    height: 40px;
    border: 3px solid var(--border-color);
    border-top-color: var(--primary-color);
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-bottom: 20px;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .error-panel p {
    color: var(--danger-color);
    font-size: 16px;
  }

  .tab-nav {
    display: flex;
    gap: 8px;
    padding: 16px 20px;
    background: white;
    border-bottom: 1px solid var(--border-color);
    overflow-x: auto;
  }

  .tab-btn {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 12px 20px;
    border: none;
    background: transparent;
    color: var(--text-secondary);
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    border-radius: 8px;
    transition: all 0.2s;
    white-space: nowrap;
  }

  .tab-btn:hover {
    background: var(--bg-color);
    color: var(--text-primary);
  }

  .tab-btn.active {
    background: var(--primary-color);
    color: white;
  }

  .tab-icon {
    font-size: 16px;
  }

  .main-content {
    flex: 1;
    padding: 20px;
    overflow-y: auto;
  }
</style>
