// ValveLogic/src/components/layout/Sidebar.tsx
import React from 'react';
import { LayoutDashboard, Network, ToggleLeft, BarChart3, Settings } from 'lucide-react';

type Route = 'dashboard' | 'network' | 'valves' | 'analysis' | 'settings';

const navItems: { id: Route; label: string; icon: React.ElementType }[] = [
  { id: 'dashboard', label: '监控面板', icon: LayoutDashboard },
  { id: 'network', label: '管网建模', icon: Network },
  { id: 'valves', label: '阀门控制', icon: ToggleLeft },
  { id: 'analysis', label: '数据分析', icon: BarChart3 },
  { id: 'settings', label: '系统设置', icon: Settings },
];

interface SidebarProps {
  currentRoute: Route;
  onNavigate: (route: Route) => void;
}

export const Sidebar: React.FC<SidebarProps> = ({ currentRoute, onNavigate }) => {
  return (
    <div className="w-64 bg-slate-900 border-r border-slate-800 flex flex-col h-full">
      <div className="p-6 border-b border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-400 rounded-lg flex items-center justify-center">
            <ToggleLeft className="text-white" size={20} />
          </div>
          <div>
            <h1 className="text-white font-bold text-lg">ValveLogic</h1>
            <p className="text-xs text-slate-400">水锤效应仿真系统</p>
          </div>
        </div>
      </div>

      <nav className="flex-1 p-4 space-y-1">
        {navItems.map((item) => (
          <button
            key={item.id}
            onClick={() => onNavigate(item.id)}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-all ${
              currentRoute === item.id
                ? 'bg-blue-600/20 text-blue-400 border border-blue-500/30'
                : 'text-slate-400 hover:bg-slate-800 hover:text-white'
            }`}
          >
            <item.icon size={18} />
            <span className="font-medium">{item.label}</span>
          </button>
        ))}
      </nav>

      <div className="p-4 border-t border-slate-800">
        <div className="bg-slate-800/50 rounded-lg p-3">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
            <span className="text-xs text-green-400">系统运行正常</span>
          </div>
          <p className="text-xs text-slate-500">版本 1.0.0</p>
        </div>
      </div>
    </div>
  );
};

// CableLink/src/components/layout/Sidebar.svelte
<script lang="ts">
  let { currentRoute, onNavigate } = $props<{
    currentRoute: string;
    onNavigate: (route: string) => void;
  }>();

  let isCollapsed = $state(false);

  const menuItems = [
    { id: '/', label: '监控总览', icon: '📊' },
    { id: '/prediction', label: '预测分析', icon: '🔮' },
    { id: '/history', label: '历史数据', icon: '📈' },
    { id: '/alerts', label: '告警中心', icon: '⚠️' },
    { id: '/settings', label: '系统设置', icon: '⚙️' }
  ];
</script>

<aside
  class={`h-screen bg-space-gray/95 backdrop-blur-xl border-r border-tech-cyan/10 flex flex-col transition-all duration-300 ${
    isCollapsed ? 'w-16' : 'w-64'
  }`}
>
  <div class="p-4 border-b border-tech-cyan/10">
    <div class="flex items-center gap-3">
      <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-deep-sea to-tech-cyan flex items-center justify-center text-lg font-bold text-white shrink-0">
        C
      </div>
      {#if !isCollapsed}
        <div>
          <h1 class="font-bold text-white text-lg">CableLink</h1>
          <p class="text-xs text-gray-400">海缆温控系统</p>
        </div>
      {/if}
    </div>
  </div>

  <nav class="flex-1 py-4 overflow-y-auto">
    <ul class="space-y-1 px-2">
      {#each menuItems as item}
        <li>
          <button
            onclick={() => onNavigate(item.id)}
            class={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 ${
              currentRoute === item.id
                ? 'bg-tech-cyan/20 text-tech-cyan shadow-lg shadow-tech-cyan/10'
                : 'text-gray-400 hover:bg-space-light hover:text-white'
            }`}
          >
            <span class="text-xl">{item.icon}</span>
            {#if !isCollapsed}
              <span class="font-medium text-sm">{item.label}</span>
            {/if}
          </button>
        </li>
      {/each}
    </ul>
  </nav>

  <div class="p-4 border-t border-tech-cyan/10">
    <button
      onclick={() => isCollapsed = !isCollapsed}
      class="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-gray-400 hover:bg-space-light hover:text-white transition-colors"
    >
      <svg
        class={`w-5 h-5 transition-transform ${isCollapsed ? 'rotate-180' : ''}`}
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 19l-7-7 7-7m8 14l-7-7 7-7" />
      </svg>
    </button>
  </div>
</aside>
