// VertiPulset/src/components/ui/StatCard.tsx
import { cn } from '@/utils/format';

interface StatCardProps {
  label: string;
  value: string | number;
  unit?: string;
  trend?: number;
  status?: 'normal' | 'warning' | 'error';
  icon?: React.ReactNode;
  className?: string;
}

export function StatCard({ label, value, unit, trend, status = 'normal', icon, className }: StatCardProps) {
  const statusColors = {
    normal: 'text-status-green',
    warning: 'text-alert-orange',
    error: 'text-red-500'
  };

  return (
    <div className={cn(
      'glass-card p-4 relative overflow-hidden',
      className
    )}>
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-electric-blue/0 via-electric-blue to-electric-blue/0"></div>
      
      <div className="flex items-start justify-between">
        <div>
          <p className="text-xs text-metal-gray mb-1">{label}</p>
          <div className="flex items-baseline gap-1">
            <span className={cn(
              'text-2xl font-bold font-display',
              statusColors[status]
            )}>
              {value}
            </span>
            {unit && <span className="text-xs text-metal-gray">{unit}</span>}
          </div>
          {trend !== undefined && (
            <div className={cn(
              'text-xs mt-1 flex items-center gap-1',
              trend >= 0 ? 'text-status-green' : 'text-alert-orange'
            )}>
              <span>{trend >= 0 ? '↑' : '↓'}</span>
              <span>{Math.abs(trend)}%</span>
            </div>
          )}
        </div>
        {icon && (
          <div className="p-2 rounded-lg bg-electric-blue/10 text-electric-blue">
            {icon}
          </div>
        )}
      </div>
    </div>
  );
}

// BeltNexus/src/components/dashboard/StatCard.tsx
import { Component } from 'solid-js';
import { formatNumber } from '@/utils/format';

interface StatCardProps {
  title: string;
  value: number;
  unit: string;
  icon: string;
  color?: 'blue' | 'green' | 'yellow' | 'red';
  trend?: number;
  decimals?: number;
}

export const StatCard: Component<StatCardProps> = (props) => {
  const colorClasses = {
    blue: 'from-industrial-500/20 to-industrial-600/20 border-industrial-500/30',
    green: 'from-green-500/20 to-green-600/20 border-green-500/30',
    yellow: 'from-yellow-500/20 to-yellow-600/20 border-yellow-500/30',
    red: 'from-red-500/20 to-red-600/20 border-red-500/30',
  };

  const iconColors = {
    blue: 'text-industrial-400',
    green: 'text-green-400',
    yellow: 'text-yellow-400',
    red: 'text-red-400',
  };

  return (
    <div
      class={`relative overflow-hidden rounded-xl border bg-gradient-to-br p-4 backdrop-blur-sm transition-all duration-300 hover:scale-[1.02] hover:shadow-lg ${
        colorClasses[props.color || 'blue']
      }`}
    >
      <div class="absolute top-0 right-0 h-20 w-20 opacity-10">
        <svg viewBox="0 0 24 24" fill="currentColor" class={iconColors[props.color || 'blue']}>
          <path d={props.icon} />
        </svg>
      </div>
      
      <div class="relative z-10">
        <div class="text-sm text-gray-400 mb-1">{props.title}</div>
        <div class="flex items-baseline gap-2">
          <span class="text-2xl font-bold font-mono text-white">
            {formatNumber(props.value, props.decimals ?? 1)}
          </span>
          <span class="text-sm text-gray-400">{props.unit}</span>
        </div>
        {props.trend !== undefined && (
          <div class={`mt-1 text-xs ${props.trend >= 0 ? 'text-green-400' : 'text-red-400'}`}>
            {props.trend >= 0 ? '↑' : '↓'} {Math.abs(props.trend).toFixed(1)}%
          </div>
        )}
      </div>
    </div>
  );
};
