// PetLink/src/components/Modal.tsx
'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
  maxWidth?: string;
}

export default function Modal({ isOpen, onClose, title, children, maxWidth = 'max-w-lg' }: ModalProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/50 backdrop-blur-sm"
            onClick={onClose}
          />
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className={`relative ${maxWidth} w-full mx-4 bg-white rounded-2xl shadow-2xl overflow-hidden`}
          >
            <div className="flex items-center justify-between p-6 border-b border-slate-100">
              <h2 className="font-poppins font-semibold text-lg text-slate-800">{title}</h2>
              <button
                onClick={onClose}
                className="p-2 rounded-lg hover:bg-slate-100 transition-colors"
              >
                <X className="w-5 h-5 text-slate-500" />
              </button>
            </div>
            <div className="p-6">{children}</div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}

// AirCargoNexust/src/components/Modal.svelte
<script lang="ts">
  import { X } from 'lucide-svelte';

  let {
    open = $bindable(false),
    title = '',
    size = 'md' as 'sm' | 'md' | 'lg' | 'xl',
    children,
    footer
  }: {
    open?: boolean;
    title?: string;
    size?: 'sm' | 'md' | 'lg' | 'xl';
    children?: any;
    footer?: any;
  } = $props();

  const sizeClasses: Record<string, string> = {
    sm: 'max-w-md',
    md: 'max-w-2xl',
    lg: 'max-w-4xl',
    xl: 'max-w-6xl'
  };

  function handleClose() {
    open = false;
  }
</script>

{#if open}
  <div class="fixed inset-0 z-50 flex items-center justify-center">
    <div 
      class="absolute inset-0 backdrop-blur-sm"
      style="background: rgba(0, 0, 0, 0.6);"
      onclick={handleClose}
    />
    <div 
      class="relative z-10 w-full mx-4 glass-panel animate-in fade-in zoom-in-95 duration-200 {sizeClasses[size]}"
    >
      <div class="flex items-center justify-between px-6 py-4 border-b border-dark-600">
        <h3 class="font-display font-semibold text-white text-lg">{title}</h3>
        <button 
          onclick={handleClose}
          class="p-1 hover:bg-dark-600 rounded transition-colors"
        >
          <X class="w-5 h-5 text-gray-400" />
        </button>
      </div>
      <div class="p-6">
        {@render children?.()}
      </div>
      {#if footer}
        <div class="px-6 py-4 border-t border-dark-600 flex justify-end gap-3">
          {@render footer?.()}
        </div>
      {/if}
    </div>
  </div>
{/if}
