// SmartGridFlow/src/components/shared/ProgressBar.tsx
import { Component } from 'solid-js';

interface ProgressBarProps {
  value: number;
  max?: number;
  color?: 'blue' | 'green' | 'red' | 'yellow';
  showLabel?: boolean;
  height?: string;
}

export const ProgressBar: Component<ProgressBarProps> = (props) => {
  const colorClasses = {
    blue: 'bg-blue-500',
    green: 'bg-green-500',
    red: 'bg-red-500',
    yellow: 'bg-yellow-500',
  };

  const percentage = () => Math.min(100, (props.value / (props.max || 1)) * 100);

  return (
    <div class="w-full">
      <div
        class={`w-full bg-gray-200 rounded-full overflow-hidden`}
        style={{ height: props.height || '8px' }}
      >
        <div
          class={`h-full ${colorClasses[props.color || 'blue']} transition-all duration-500`}
          style={{ width: `${percentage()}%` }}
        />
      </div>
      {props.showLabel && (
        <div class="text-right text-sm text-gray-600 mt-1">{percentage().toFixed(1)}%</div>
      )}
    </div>
  );
};

// AirCargoNexust/src/components/ProgressBar.svelte
<script lang="ts">
  let {
    value,
    max = 100,
    showLabel = true,
    status = 'normal' as 'normal' | 'warning' | 'danger'
  }: {
    value: number;
    max?: number;
    showLabel?: boolean;
    status?: 'normal' | 'warning' | 'danger';
  } = $props();

  let percentage = $derived(Math.min(100, Math.max(0, (value / max) * 100)));
</script>

<div class="w-full">
  {#if showLabel}
    <div class="flex justify-between text-xs mb-1">
      <span class="text-gray-400">进度</span>
      <span class="text-white font-mono">{value.toLocaleString()} / {max.toLocaleString()}</span>
    </div>
  {/if}
  <div class="h-2 bg-dark-700 rounded-full overflow-hidden">
    <div 
      class="h-full rounded-full transition-all duration-300"
      class:bg-alert-green={status === 'normal'}
      class:bg-alert-orange={status === 'warning'}
      class:bg-alert-red={status === 'danger'}
      style="width: {percentage}%"
    ></div>
  </div>
</div>
