// UAVScan/src/components/layout/Sidebar.vue
<template>
  <aside
    class="h-full bg-cyber-bg-light border-r border-cyber-border flex flex-col transition-all duration-300"
    :class="collapsed ? 'w-16' : 'w-64'"
  >
    <div class="p-4 border-b border-cyber-border flex items-center gap-3">
      <div class="w-10 h-10 rounded-lg bg-gradient-to-br from-electric-blue to-electric-blue-dark flex items-center justify-center flex-shrink-0">
        <component :is="icons.ScanLine" class="w-6 h-6 text-cyber-bg" />
      </div>
      <transition name="fade">
        <div v-if="!collapsed" class="flex flex-col">
          <span class="font-bold text-lg text-cyber-text tracking-wide">UAVScan</span>
          <span class="text-xs text-cyber-text-secondary">点云降维中枢</span>
        </div>
      </transition>
    </div>

    <nav class="flex-1 p-2 overflow-y-auto">
      <ul class="space-y-1">
        <li v-for="item in menuItems" :key="item.path">
          <router-link
            :to="item.path"
            class="flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 group"
            :class="{
              'bg-electric-blue/10 text-electric-blue border border-electric-blue/30': isActive(item.path),
              'text-cyber-text-secondary hover:text-cyber-text hover:bg-cyber-bg-lighter': !isActive(item.path)
            }"
          >
            <component
              :is="icons[item.icon]"
              class="w-5 h-5 flex-shrink-0 transition-transform duration-200"
              :class="{ 'group-hover:scale-110': !isActive(item.path) }"
            />
            <transition name="fade">
              <span v-if="!collapsed" class="text-sm font-medium truncate">{{ item.label }}</span>
            </transition>
            <transition name="fade">
              <span
                v-if="!collapsed && item.badge"
                class="ml-auto text-xs px-1.5 py-0.5 rounded-full bg-electric-blue/20 text-electric-blue"
              >
                {{ item.badge }}
              </span>
            </transition>
          </router-link>
        </li>
      </ul>
    </nav>

    <div class="p-2 border-t border-cyber-border">
      <button
        @click="$emit('toggle')"
        class="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-cyber-text-secondary hover:text-cyber-text hover:bg-cyber-bg-lighter transition-all duration-200"
      >
        <component
          :is="collapsed ? icons.ChevronRight : icons.ChevronLeft"
          class="w-5 h-5"
        />
        <transition name="fade">
          <span v-if="!collapsed" class="text-sm">收起菜单</span>
        </transition>
      </button>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import {
  LayoutDashboard,
  Cpu,
  Box,
  RefreshCw,
  Camera,
  Settings,
  ScanLine,
  ChevronLeft,
  ChevronRight
} from 'lucide-vue-next'
import { useTaskStore, useSyncStore } from '@/stores'

const props = defineProps<{
  collapsed: boolean
}>()

defineEmits<{
  toggle: []
}>()

const route = useRoute()
const taskStore = useTaskStore()
const syncStore = useSyncStore()

const icons = {
  LayoutDashboard,
  Cpu,
  Box,
  RefreshCw,
  Camera,
  Settings,
  ScanLine,
  ChevronLeft,
  ChevronRight
}

const menuItems = computed(() => [
  {
    path: '/dashboard',
    label: '数据仪表盘',
    icon: 'LayoutDashboard'
  },
  {
    path: '/processing',
    label: '处理中心',
    icon: 'Cpu',
    badge: taskStore.runningTasks.length > 0 ? taskStore.runningTasks.length : undefined
  },
  {
    path: '/visualizer',
    label: '点云可视化',
    icon: 'Box'
  },
  {
    path: '/sync',
    label: '数据同步',
    icon: 'RefreshCw',
    badge: syncStore.syncingTasks.length > 0 ? syncStore.syncingTasks.length : undefined
  },
  {
    path: '/snapshots',
    label: '快照管理',
    icon: 'Camera'
  },
  {
    path: '/settings',
    label: '系统设置',
    icon: 'Settings'
  }
])

function isActive(path: string): boolean {
  return route.path === path || route.path.startsWith(path + '/')
}
</script>

// AirCargoNexust/src/components/Sidebar.svelte
<script lang="ts">
  import Link from '@/router/Link.svelte';
  import { currentRoute } from '@/router';
  import { 
    Box, 
    Package, 
    Calculator, 
    Camera, 
    Settings, 
    PlaneTakeoff,
    ChevronRight
  } from 'lucide-svelte';

  let isCollapsed = $state(false);

  const navItems = [
    { path: '/', icon: Box, label: '货舱可视化' },
    { path: '/cargo', icon: Package, label: '货物管理' },
    { path: '/calculate', icon: Calculator, label: '配载计算' },
    { path: '/snapshots', icon: Camera, label: '配载快照' },
    { path: '/cockpit', icon: PlaneTakeoff, label: '机组终端' }
  ];
</script>

<aside 
  class="h-full flex flex-col bg-dark-800 border-r border-dark-600 transition-all duration-300"
  class:is-collapsed={isCollapsed}
  style="width: {isCollapsed ? '64px' : '240px'}"
>
  <div class="p-4 border-b border-dark-600 flex items-center justify-between">
    <div class="flex items-center gap-3 overflow-hidden">
      <div class="w-10 h-10 rounded-lg bg-aviation-700 flex items-center justify-center flex-shrink-0">
        <PlaneTakeoff class="w-6 h-6 text-white" />
      </div>
      {#if !isCollapsed}
        <div class="whitespace-nowrap">
          <div class="font-display font-bold text-white text-lg leading-tight">AirCargo</div>
          <div class="text-xs text-gray-400">Nexus v1.0</div>
        </div>
      {/if}
    </div>
    <button 
      onclick={() => isCollapsed = !isCollapsed}
      class="p-1 hover:bg-dark-600 rounded transition-colors flex-shrink-0"
    >
      <ChevronRight 
        class="w-5 h-5 text-gray-400 transition-transform"
        style="transform: rotate({isCollapsed ? '0deg' : '180deg'})"
      />
    </button>
  </div>

  <nav class="flex-1 py-4 overflow-y-auto">
    <ul class="space-y-1 px-2">
      {#each navItems as item}
        <li>
          <Link 
            to={item.path}
            class={`flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 ${
              $currentRoute === item.path
                ? 'bg-aviation-700 text-white' 
                : 'text-gray-400 hover:text-white hover:bg-dark-700'
            }`}
          >
            {#if $currentRoute === item.path}
              <div class="absolute left-0 top-0 bottom-0 w-1 bg-aviation-500 rounded-r"></div>
            {/if}
            <svelte:component this={item.icon} class="w-5 h-5 flex-shrink-0" />
            {#if !isCollapsed}
              <span class="text-sm whitespace-nowrap">{item.label}</span>
            {/if}
          </Link>
        </li>
      {/each}
    </ul>
  </nav>

  <div class="p-4 border-t border-dark-600">
    <button 
      class="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-400 hover:text-white hover:bg-dark-700 transition-colors"
    >
      <Settings class="w-5 h-5 flex-shrink-0" />
      {#if !isCollapsed}
        <span class="text-sm whitespace-nowrap">系统设置</span>
      {/if}
    </button>
  </div>
</aside>
