// CyberNexus/src/presentation/components/ui/StatsCard.tsx
import type { Component, JSX } from 'solid-js';

interface StatsCardProps {
  icon: string;
  label: string;
  value: number | string;
  trend?: {
    value: number;
    label: string;
  };
  color?: 'blue' | 'green' | 'yellow' | 'red' | 'purple';
  children?: JSX.Element;
}

const colorClasses: Record<string, string> = {
  blue: 'bg-blue-900 text-blue-300',
  green: 'bg-green-900 text-green-300',
  yellow: 'bg-yellow-900 text-yellow-300',
  red: 'bg-red-900 text-red-300',
  purple: 'bg-purple-900 text-purple-300',
};

export const StatsCard: Component<StatsCardProps> = (props) => {
  const color = props.color || 'blue';

  return (
    <div class="bg-gray-800 rounded-lg p-6 border border-gray-700">
      <div class="flex items-start justify-between">
        <div>
          <p class="text-gray-400 text-sm">{props.label}</p>
          <p class="text-2xl font-bold text-white mt-1">{props.value}</p>
          {props.trend && (
            <p class={`text-xs mt-2 ${props.trend.value >= 0 ? 'text-green-400' : 'text-red-400'}`}>
              {props.trend.value >= 0 ? '↑' : '↓'} {Math.abs(props.trend.value)}% {props.trend.label}
            </p>
          )}
        </div>
        <div class={`w-12 h-12 ${colorClasses[color]} rounded-full flex items-center justify-center`}>
          <span class="text-2xl">{props.icon}</span>
        </div>
      </div>
      {props.children && <div class="mt-4">{props.children}</div>}
    </div>
  );
};

// SafeHarbor/src/components/StatsCard.tsx
import React from 'react';

interface StatsCardProps {
  title: string;
  value: string | number;
  unit?: string;
  icon: React.ReactNode;
  gradient: string;
  trend?: {
    value: number;
    isUp: boolean;
  };
}

export const StatsCard: React.FC<StatsCardProps> = ({
  title,
  value,
  unit,
  icon,
  gradient,
  trend
}) => {
  return (
    <div className={`stat-card ${gradient}`}>
      <div className="flex justify-between items-start mb-4">
        <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center">
          {icon}
        </div>
        {trend && (
          <div className={`flex items-center gap-1 text-sm ${trend.isUp ? 'text-green-200' : 'text-red-200'}`}>
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d={trend.isUp ? 'M5 10l7-7m0 0l7 7m-7-7v18' : 'M19 14l-7 7m0 0l-7-7m7 7V3'}
              />
            </svg>
            <span>{trend.value}%</span>
          </div>
        )}
      </div>
      <div className="stat-value">
        {value}
        {unit && <span className="text-lg ml-1 opacity-80">{unit}</span>}
      </div>
      <div className="stat-label mt-1">{title}</div>
    </div>
  );
};
